### ISSUE TITLE
replaceTransaction fails due to wrong logic

### ISSUE THREAD

**Issue by yashh** [ethereum/web3.py#1084]
* Version: 4.5.0
* Python: 3.6.5
* OS: Ubuntu

### replaceTransaction fails

web3.eth.replaceTransaction(txid, new_transaction)
calls `prepare_replacement_transaction(web3, current_transaction, new_transaction)` internally.
`current_transaction` is a `AttributeDict` which has `blockHash` set to `HexBytes('0x000000....')`

But `prepare_replacement_transaction` checks `blockHash` for None.
`if current_transaction['blockHash'] is not None:`

### How can it be fixed?

It should check for None or HexBytes('0x0000')..

**Comment by pipermerriam** [comment]
Without having done any digging, my first instinct is to fix `current_transaction` have `blockHash` set to `None` for unmined transactions as setting it to the the null hash seems wrong (especially since the parent block to the genesis block is always the null hash and thus this could lead to other types of errors.

**Comment by yashh** [comment]
Right now I am using `web3.eth.getTransaction` to get the current pendingTransaction. It has blockHash set to `HexBytes('0x000...'). I can set it None or pop it of the dictionary. Thanks @pipermerriam

**Comment by carver** [comment]
What type of node are you connected to @yashh ? This might be a thing where different clients return different `blockHash` values for an unmined transaction.
