### ISSUE TITLE
How to parse erc20 token transfer

### ISSUE THREAD

**Issue by 631068264** [ethereum/web3.py#1171]
* Version: 4.8.2
* Python: 3.6.5
* OS: osx
![image](https://user-images.githubusercontent.com/8144089/50263233-b5c49e80-044f-11e9-8438-2744767aea6b.png)

TX hash 0xea93834abbb84cf41f7b2bada743bdc2b2dd7144265ef436eaa751cb6f1428b2

**Comment by carver** [comment]
Roughly, you'll want to create a contract instance bound to the address you're interested in, and monitor for Transfer events. The results will have parsed data for you.

---

Since this isn't a bug or feature request for Web3.py, I'm closing the issue. But feel free to continue discussing here. One alternative to consider is https://ethereum.stackexchange.com

You will get better & faster answers if your question has a minimal, complete, and verifiable example: https://stackoverflow.com/help/mcve
