### ISSUE TITLE
Does web3.py support array as function input parameter?

### ISSUE THREAD

**Issue by xiliyuan** [ethereum/web3.py#1248]
The contract is:
```
pragma solidity ^0.4.25;

contract Public_external {
    function pub(uint[20] a) public returns (uint) {
         return a[10]*2;
    }

    function ext(uint[20] a) external returns (uint) {
         return a[10]*2;
    }
}
```
How can I put input valuse through web3.py?

I read one similar solution. 
[How to send a python bytearray into solidity function by web3.py?](https://ethereum.stackexchange.com/questions/59185/how-to-send-a-python-bytearray-into-solidity-function-by-web3-py)

However, it seems this solution does not use web3.py module. This solution converts data into bytearray manually. 

How can I use web3.py to do the same thing?

**Comment by kclowes** [comment]
The stack overflow solution you posted uses web3.py. I am not sure what you are trying to accomplish. 

You can call a contract function like: 
`contract.functions.<function_name>(<argument>).call()`

In your case since `a` is an array of 20 integers, for example: `a = [1, 2, 3, 4, ... , 20]`, you'd say:
`contract.functions.pub(a).call()` which will return 22

[This page](https://web3py.readthedocs.io/en/stable/contracts.html) has an example you might find useful. Feel free to reopen with a more specific question if you need.

**Comment by ChiHangChen** [comment]
HI, I have a contract funciont called `batch_mint` which accept `string[]` as input
![image](https://user-images.githubusercontent.com/22412708/169676393-5a776ec0-0c7b-4f30-8ab9-62c2038ef519.png)

I want to call it with web3.py, I tried with the following API
```
transaction = token_contract.functions.batch_mint(
    to=Web3.toChecksumAddress("0xxxxx"),
    metadata_IPFS_CIDs=["AAA", "BBB"],
).buildTransaction(
    {
        'gas': 70000,
        'gasPrice': w3.toWei('1', 'gwei'),
        'from': Web3.toChecksumAddress(my_account.address),
        'nonce': nonce
    }
) 
```
But I keep getting the error

```
ValidationError: 
Could not identify the intended function with name `batch_mint`, positional argument(s) of type `(<class 'hexbytes.main.HexBytes'>,)` and keyword argument(s) of type `{}`.
Found 1 function(s) with the name `batch_mint`: ['batch_mint(address,string[])']
Function invocation failed due to improper number of arguments.
```

How can I send the parameter input correctly?
