### ISSUE TITLE
Support for Weighted Gas Price Strategy

### ISSUE THREAD

**Issue by Jmjin** [ethereum/web3.py#1463]
### What was wrong?

`construct_time_based_gas_price_strategy` is unable to handle cases when network suddenly requires higher gas prices due to many variables such as network congestion. This has resulted in more transactions to revert.

### How can it be fixed?

Currently `construct_time_based_gas_price_strategy` does not factor in weighting when looking over a sample of X number of blocks. If the calculation is weighted towards more recent blocks, `construct_time_based_gas_price_strategy` should be able to handle similars cases like the one mentioned in `What was wrong`.

**Comment by tmckenzie51** [comment]
Hi. I'm interested in working on this issue. I notice that in the construct_time_based_gas_price strategy function that it takes as a parameter 'sample size'. I understand based on your description, that we would want to weight the price towards more recent blocks. What exactly influences this weight? Is it the price associated with the more recent blocks, or the amount of time associated with the more recent blocks? I'm a bit confused about this and would appreciate any help and/or clarification. Thank you.

**Comment by Jmjin** [comment]
> Hi. I'm interested in working on this issue. I notice that in the construct_time_based_gas_price strategy function that it takes as a parameter 'sample size'. I understand based on your description, that we would want to weight the price towards more recent blocks. What exactly influences this weight? Is it the price associated with the more recent blocks, or the amount of time associated with the more recent blocks? I'm a bit confused about this and would appreciate any help and/or clarification. Thank you.

Hey @tmckenzie51 I believe it's the latter. Weighting should be favored more towards the time associated with the more recent blocks.

**Comment by ulope** [comment]
Is there a reason this has been closed? 
This is still a problem (esp. at the moment with very high and fluctuating gas prices on mainnet).

**Comment by pipermerriam** [comment]
@Jmjin historically the weighted gas price strategy was written at a time when this problem was just starting to show up and certainly was not well understood.  Since then it has become clear (to me at least) that gas pricing is a very subjective area.  Because of this, I'm inclined to focus on ensuring that the gas pricing strategy API is well suited for 3rd party extension and to encourage the community to publish their own gas price strategies for different use cases.  If any of these proves broadly useful we can look into including it in the core set of tools that the web3 library provides.
