### ISSUE TITLE
get_new_entries alaways return empty and get_all_entries raise exception

### ISSUE THREAD

**Issue by we4p0x** [ethereum/web3.py#1485]
* Version: 5.2.2
* Python: 3.6.8
* OS: linux

### What was wrong?

I use example code
https://web3py.readthedocs.io/en/latest/filters.html#examples-listening-for-events

```python
from web3 import Web3

w3 = Web3(Web3.IPCProvider('/data/ethereum/geth.ipc'))
#w3 = Web3(Web3.WebsocketProvider('wss://mainnet.infura.io/ws'))
print(w3.isConnected())
print(w3.clientVersion)

new_block_filter = w3.eth.filter('latest')
print(new_block_filter.get_new_entries())
print(new_block_filter.get_all_entries())
```
*get_new_entries* returns *[]* and *get_all_entries* raise exception *ValueError: {'code': -32000, 'message': 'filter not found'}*
  
than I change to websocket

```python
w3 = Web3(Web3.WebsocketProvider('wss://mainnet.infura.io/ws'))
```

and error once again.

```bash
cat@cat:~/eth_backend$ python3 d.py 
True
Geth/v1.9.6-stable-bd059680/linux-amd64/go1.13.1
[]
Traceback (most recent call last):
  File "d.py", line 13, in <module>
    print(new_transaction_filter.get_all_entries())
  File "/usr/local/lib/python3.6/dist-packages/web3/_utils/filters.py", line 125, in get_all_entries
    log_entries = self._filter_valid_entries(self.web3.eth.getFilterLogs(self.filter_id))
  File "/usr/local/lib/python3.6/dist-packages/web3/eth.py", line 407, in getFilterLogs
    "eth_getFilterLogs", [filter_id],
  File "/usr/local/lib/python3.6/dist-packages/web3/manager.py", line 97, in request_blocking
    raise ValueError(response["error"])
ValueError: {'code': -32000, 'message': 'filter not found'}
```

**Comment by kclowes** [comment]
@we4p0x Infura doesn't support filters, which explains the error there. I will dig in a little bit more tomorrow on the geth side because I think there may be something going on with the `getFilterLogs` method. In the meantime you might try polling `w3.eth.getFilterChanges(filter_id)`. @pipermerriam do you have any ideas here?

**Comment by pipermerriam** [comment]
@kclowes infura definitely doesn't support filters over http, but it *might* support them over websockets but I'm not sure about that.

**Comment by kclowes** [comment]
Oh you're right, Infura does support filters over websockets. 

I was able to do some digging and I'm not sure why, but it looks like Geth, Parity, and Infura all return a `filter not found` error when a filter is set up using either the `pending` or `latest` arguments, and then `get_all_entries` is called. For example: 

``` python
>>> f = w3.eth.filter('latest')
>>> f.get_all_entries()
# returns FilterNotFound
```
or 
``` python
>>> f = w3.eth.filter('pending')
>>> f.get_all_entries()
# returns FilterNotFound
```
However, if you add a dictionary to the request with at least one of the keys `fromBlock`, `toBlock`, `address`, and/or `topic`, you should get some data back. For example: 

``` python
>>> f = w3.eth.filter({"fromBlock": 8891745, "toBlock": 8891745})
>>> f.get_all_entries()
# should return some data
```

It seems to me that for whatever reason, `eth_getFilterLogs` (the JSON-RPC method behind `get_all_entries`) doesn't work when a filter is set up using the `eth_newBlockFilter` and `eth_newPendingTransactionFilter` methods, and if you set up a filter with `eth_newBlockFilter` or `eth_newPendingTransactionFilter` (as shown in the top two code blocks) you need to poll with `eth_getFilterChanges` (which is `filter.get_new_entries()` in web3) instead of using `eth_getFilterLogs` (or `filter.get_all_entries()`). But, if you set up the filter using `eth_newFilter`, you should consistently get data back using `filter.get_all_entries()`. `eth_newFilter` is the JSON-RPC method that gets called if you pass in a dict to `w3.eth.filter`, as shown in the third code block.

The other complicating factor is that the node may delete the filter at any time. See [this stackoverflow question/answer](https://ethereum.stackexchange.com/questions/41129/web3-eth-getfilterchangesweb3-filter-filter-id-throws-filter-not-found). You may try adding the [local_filter_middleware](https://web3py.readthedocs.io/en/stable/middleware.html#locally-managed-log-and-block-filters) to shift the filter logic to the web3 instance rather than the node. 

I'm going to close this issue because I don't think this is a web3 problem since I get the same behavior when I take web3 out of the picture and use `wscat` to make requests to local Geth and Parity nodes and Infura nodes as well. Feel free to reopen if you feel I'm mistaken and feel free to continue the conversation if this giant block of text doesn't make sense!

**Comment by HameedFawwaz** [comment]
I am having a really weird issue. About a month ago I created a PairCreated event in web3.py and I used geth, and that worked. I try it about a month later using both HTTP and WS infura, and it returns an empty array. I believed that I also tried it in geth a few weeks ago and it also returned an empty array. 

`
web3 = Web3(Web3.WebsocketProvider("wss://mainnet.infura.io/ws/v3/eb8d899d09ac4fd6b440f05beced01bc"))
print(web3.isConnected())

event_filter = pair_contract.events.PairCreated.createFilter(fromBlock="latest")
print(event_filter.get_all_entries())
print(web3.eth.get_filter_logs(event_filter.filter_id))`
