### ISSUE TITLE
Unable to call contract functions

### ISSUE THREAD

**Issue by amitsharma8891** [ethereum/web3.py#1550]
* Version: 5.3.0
* Python: 3.7
* OS: osx

Trying to get the balance of address of this address : '0x3dE11FE8E6d0E20ff5CEA0BaA625939194Df2482'
`address = '0x3dE11FE8E6d0E20ff5CEA0BaA625939194Df2482'`
`balance = self.contract_address.functions.balanceOf(address).call()`

```
request_func = self.provider.request_func(
AttributeError: 'list' object has no attribute 'request_func'
```
for this I am using infura ropston

I am trying to call the balanceOf function but it throws above-mentioned error. Can anyone tell where am I doing wrong.

**Comment by kclowes** [comment]
Without a few more details, I can't tell what's going on here. `provider` should just be an object rather than a list. Can you show me how you are setting up your web3 instance? For example, it should look something like:
```
from web3.auto.infura.ropsten import w3
```
or 
```
from web3 import Web3, HTTPProvider
w3 = Web3(HTTPProvider('https://ropsten.infura.io/v3/<YOUR API KEY>'))
```
The other thing that stands out to me is the naming of `contract_address`. I think should be the contract instance, so it would also be helpful if you could show me how you are setting up your web3 contract instance. 

Here is an example to work with a contract that you might find useful: https://web3py.readthedocs.io/en/stable/examples.html#working-with-an-erc20-token-contract

**Comment by amitsharma8891** [comment]
It was human error(url was wrong from my site), it's working as expected. Closing this issue. Sorry for the inconvenience.
