### ISSUE TITLE
trouble in trying to install web3.py in windows

### ISSUE THREAD

**Issue by therealwizard** [ethereum/web3.py#1578]
* Version: x.x.x
* Python: 3.7
* OS: win
* `pip install web3

```
<
Collecting web3
  Using cached web3-5.5.1-py3-none-any.whl (459 kB)
Collecting eth-account<0.5.0,>=0.4.0
  Using cached eth_account-0.4.0-py3-none-any.whl (26 kB)
Collecting lru-dict<2.0.0,>=1.1.6
  Using cached lru-dict-1.1.6.tar.gz (9.4 kB)
Requirement already satisfied: websockets<9.0.0,>=8.1.0 in c:\users\lenovo\hamada\lib\site-packages (from web3) (8.1)
Collecting eth-abi<3.0.0,>=2.0.0b6
  Using cached eth_abi-2.1.0-py3-none-any.whl (27 kB)
Collecting hexbytes<1.0.0,>=0.1.0
  Using cached hexbytes-0.2.0-py3-none-any.whl (5.3 kB)
Requirement already satisfied: eth-typing<3.0.0,>=2.0.0 in c:\users\lenovo\hamada\lib\site-packages (from web3) (2.2.1)
Requirement already satisfied: jsonschema<4.0.0,>=3.0.0 in c:\users\lenovo\hamada\lib\site-packages (from web3) (3.2.0)
Requirement already satisfied: requests<3.0.0,>=2.16.0 in c:\users\lenovo\hamada\lib\site-packages (from web3) (2.22.0)
Requirement already satisfied: pypiwin32>=223; platform_system == "Windows" in c:\users\lenovo\hamada\lib\site-packages (from web3) (223)
Requirement already satisfied: protobuf<4,>=3.10.0 in c:\users\lenovo\hamada\lib\site-packages (from web3) (3.11.2)
Requirement already satisfied: ipfshttpclient<1,>=0.4.12 in c:\users\lenovo\hamada\lib\site-packages (from web3) (0.4.12)
Collecting eth-utils<2.0.0,>=1.8.4
  Using cached eth_utils-1.8.4-py3-none-any.whl (23 kB)
Requirement already satisfied: eth-hash[pycryptodome]<1.0.0,>=0.2.0 in c:\users\lenovo\hamada\lib\site-packages (from web3) (0.2.0)
Collecting eth-keyfile<0.6.0,>=0.5.0
  Using cached eth_keyfile-0.5.1-py3-none-any.whl (8.3 kB)
Requirement already satisfied: attrdict<3,>=2.0.0 in c:\users\lenovo\hamada\lib\site-packages (from eth-account<0.5.0,>=0.4.0->web3) (2.0.1)
Collecting rlp<2,>=1.0.0
  Using cached rlp-1.2.0-py2.py3-none-any.whl (19 kB)
Collecting eth-rlp<1,>=0.1.2
  Using cached eth_rlp-0.1.2-py3-none-any.whl (6.5 kB)
Collecting eth-keys<0.3.0,>=0.2.1
  Using cached eth_keys-0.2.4-py3-none-any.whl (24 kB)
Requirement already satisfied: parsimonious<0.9.0,>=0.8.0 in c:\users\lenovo\hamada\lib\site-packages (from eth-abi<3.0.0,>=2.0.0b6->web3) (0.8.1)
Requirement already satisfied: attrs>=17.4.0 in c:\users\lenovo\hamada\lib\site-packages (from jsonschema<4.0.0,>=3.0.0->web3) (19.3.0)
Requirement already satisfied: pyrsistent>=0.14.0 in c:\users\lenovo\hamada\lib\site-packages (from jsonschema<4.0.0,>=3.0.0->web3) (0.15.7)
Requirement already satisfied: six>=1.11.0 in c:\users\lenovo\hamada\lib\site-packages (from jsonschema<4.0.0,>=3.0.0->web3) (1.14.0)
Requirement already satisfied: setuptools in c:\users\lenovo\hamada\lib\site-packages (from jsonschema<4.0.0,>=3.0.0->web3) (45.1.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\lenovo\hamada\lib\site-packages (from requests<3.0.0,>=2.16.0->web3) (2019.11.28)
Requirement already satisfied: idna<2.9,>=2.5 in c:\users\lenovo\hamada\lib\site-packages (from requests<3.0.0,>=2.16.0->web3) (2.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\lenovo\hamada\lib\site-packages (from requests<3.0.0,>=2.16.0->web3) (1.25.7)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\lenovo\hamada\lib\site-packages (from requests<3.0.0,>=2.16.0->web3) (3.0.4)
Requirement already satisfied: pywin32>=223 in c:\users\lenovo\hamada\lib\site-packages (from pypiwin32>=223; platform_system == "Windows"->web3) (227)
Requirement already satisfied: multiaddr>=0.0.7 in c:\users\lenovo\hamada\lib\site-packages (from ipfshttpclient<1,>=0.4.12->web3) (0.0.9)
Collecting cytoolz<1.0.0,>=0.10.1; implementation_name == "cpython"
  Using cached cytoolz-0.10.1.tar.gz (475 kB)
Requirement already satisfied: pycryptodome<4,>=3.6.6; extra == "pycryptodome" in c:\users\lenovo\hamada\lib\site-packages (from eth-hash[pycryptodome]<1.0.0,>=0.2.0->web3) (3.9.4)
Requirement already satisfied: netaddr in c:\users\lenovo\hamada\lib\site-packages (from multiaddr>=0.0.7->ipfshttpclient<1,>=0.4.12->web3) (0.7.19)
Requirement already satisfied: varint in c:\users\lenovo\hamada\lib\site-packages (from multiaddr>=0.0.7->ipfshttpclient<1,>=0.4.12->web3) (1.0.2)
Requirement already satisfied: base58 in c:\users\lenovo\hamada\lib\site-packages (from multiaddr>=0.0.7->ipfshttpclient<1,>=0.4.12->web3) (2.0.0)
Requirement already satisfied: toolz>=0.8.0 in c:\users\lenovo\hamada\lib\site-packages (from cytoolz<1.0.0,>=0.10.1; implementation_name == "cpython"->eth-utils<2.0.0,>=1.8.4->web3) (0.10.0)
Installing collected packages: cytoolz, eth-utils, eth-keys, eth-keyfile, hexbytes, rlp, eth-rlp, eth-abi, eth-account, lru-dict, web3
    Running setup.py install for cytoolz ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\lenovo\hamada\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\LENOVO\\AppData\\Local\\Temp\\pip-install-y6c8xmww\\cytoolz\\setup.py'"'"'; __file__='"'"'C:\\Users\\LENOVO\\AppData\\Local\\Temp\\pip-install-y6c8xmww\\cytoolz\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\LENOVO\AppData\Local\Temp\pip-record-dphc6qzi\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\lenovo\hamada\include\site\python3.8\cytoolz'
         cwd: C:\Users\LENOVO\AppData\Local\Temp\pip-install-y6c8xmww\cytoolz\
    Complete output (54 lines):
    [1/5] Cythonizing cytoolz/utils.pyx
    [2/5] Cythonizing cytoolz/dicttoolz.pyx
    [3/5] Cythonizing cytoolz/functoolz.pyx
    [4/5] Cythonizing cytoolz/itertoolz.pyx
    [5/5] Cythonizing cytoolz/recipes.pyx
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.8
    creating build\lib.win32-3.8\cytoolz
    copying cytoolz\compatibility.py -> build\lib.win32-3.8\cytoolz
    copying cytoolz\utils_test.py -> build\lib.win32-3.8\cytoolz
    copying cytoolz\_signatures.py -> build\lib.win32-3.8\cytoolz
    copying cytoolz\_version.py -> build\lib.win32-3.8\cytoolz
    copying cytoolz\__init__.py -> build\lib.win32-3.8\cytoolz
    creating build\lib.win32-3.8\cytoolz\curried
    copying cytoolz\curried\exceptions.py -> build\lib.win32-3.8\cytoolz\curried
    copying cytoolz\curried\operator.py -> build\lib.win32-3.8\cytoolz\curried
    copying cytoolz\curried\__init__.py -> build\lib.win32-3.8\cytoolz\curried
    copying cytoolz\dicttoolz.pyx -> build\lib.win32-3.8\cytoolz
    copying cytoolz\functoolz.pyx -> build\lib.win32-3.8\cytoolz
    copying cytoolz\itertoolz.pyx -> build\lib.win32-3.8\cytoolz
    copying cytoolz\recipes.pyx -> build\lib.win32-3.8\cytoolz
    copying cytoolz\utils.pyx -> build\lib.win32-3.8\cytoolz
    copying cytoolz\cpython.pxd -> build\lib.win32-3.8\cytoolz
    copying cytoolz\dicttoolz.pxd -> build\lib.win32-3.8\cytoolz
    copying cytoolz\functoolz.pxd -> build\lib.win32-3.8\cytoolz
    copying cytoolz\itertoolz.pxd -> build\lib.win32-3.8\cytoolz
    copying cytoolz\recipes.pxd -> build\lib.win32-3.8\cytoolz
    copying cytoolz\utils.pxd -> build\lib.win32-3.8\cytoolz
    copying cytoolz\__init__.pxd -> build\lib.win32-3.8\cytoolz
    creating build\lib.win32-3.8\cytoolz\tests
    copying cytoolz\tests\dev_skip_test.py -> build\lib.win32-3.8\cytoolz\tests
    copying cytoolz\tests\test_compatibility.py -> build\lib.win32-3.8\cytoolz\tests
    copying cytoolz\tests\test_curried.py -> build\lib.win32-3.8\cytoolz\tests
    copying cytoolz\tests\test_curried_toolzlike.py -> build\lib.win32-3.8\cytoolz\tests
    copying cytoolz\tests\test_dev_skip_test.py -> build\lib.win32-3.8\cytoolz\tests
    copying cytoolz\tests\test_dicttoolz.py -> build\lib.win32-3.8\cytoolz\tests
    copying cytoolz\tests\test_docstrings.py -> build\lib.win32-3.8\cytoolz\tests
    copying cytoolz\tests\test_doctests.py -> build\lib.win32-3.8\cytoolz\tests
    copying cytoolz\tests\test_embedded_sigs.py -> build\lib.win32-3.8\cytoolz\tests
    copying cytoolz\tests\test_functoolz.py -> build\lib.win32-3.8\cytoolz\tests
    copying cytoolz\tests\test_inspect_args.py -> build\lib.win32-3.8\cytoolz\tests
    copying cytoolz\tests\test_itertoolz.py -> build\lib.win32-3.8\cytoolz\tests
    copying cytoolz\tests\test_none_safe.py -> build\lib.win32-3.8\cytoolz\tests
    copying cytoolz\tests\test_recipes.py -> build\lib.win32-3.8\cytoolz\tests
    copying cytoolz\tests\test_serialization.py -> build\lib.win32-3.8\cytoolz\tests
    copying cytoolz\tests\test_signatures.py -> build\lib.win32-3.8\cytoolz\tests
    copying cytoolz\tests\test_tlz.py -> build\lib.win32-3.8\cytoolz\tests
    copying cytoolz\tests\test_utils.py -> build\lib.win32-3.8\cytoolz\tests
    running build_ext
    building 'cytoolz.dicttoolz' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\lenovo\hamada\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\LENOVO\\AppData\\Local\\Temp\\pip-install-y6c8xmww\\cytoolz\\setup.py'"'"'; __file__='"'"'C:\\Users\\LENOVO\\AppData\\Local\\Temp\\pip-install-y6c8xmww\\cytoolz\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\LENOVO\AppData\Local\Temp\pip-record-dphc6qzi\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\lenovo\hamada\include\site\python3.8\cytoolz' Check the logs for full command output.
>
```

### What was wrong?
trouble in installing web3
Please include any of the following that are applicable:

* The code which produced the error
* The full output of the error
* What type of node you were connecting to.

### How can it be fixed?

Fill this section in if you know how this could or should be fixed.

**Comment by pipermerriam** [comment]
If you take a look at the text of the error message:

```
    error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
```

It appears you have a system dependency that you need to install.  I'm closing this but feel free to reach back out if you are still having trouble.

**Comment by pipermerriam** [comment]
We should probably also update our quickstart/installation documentation to have this information in there.

**Comment by xerx-x** [comment]
pip install web3
Collecting web3
  Using cached web3-5.12.0-py3-none-any.whl (467 kB)
Collecting eth-abi<3.0.0,>=2.0.0b6
  Using cached eth_abi-2.1.1-py3-none-any.whl (27 kB)
Requirement already satisfied: websockets<9.0.0,>=8.1.0 in c:\python38\lib\site-packages (from web3) (8.1)
Collecting eth-account<0.6.0,>=0.5.2
  Using cached eth_account-0.5.2-py3-none-any.whl (94 kB)
Requirement already satisfied: eth-typing<3.0.0,>=2.0.0 in c:\python38\lib\site-packages (from web3) (2.2.1)
Collecting hexbytes<1.0.0,>=0.1.0
  Using cached hexbytes-0.2.1-py3-none-any.whl (6.0 kB)
Collecting ipfshttpclient<1,>=0.4.13
  Using cached ipfshttpclient-0.6.0.post1-py3-none-any.whl (200 kB)
Collecting protobuf<4,>=3.10.0
  Using cached protobuf-3.12.4-py2.py3-none-any.whl (443 kB)
Requirement already satisfied: jsonschema<4.0.0,>=3.2.0 in c:\python38\lib\site-packages (from web3) (3.2.0)
Collecting lru-dict<2.0.0,>=1.1.6
  Using cached lru-dict-1.1.6.tar.gz (9.4 kB)
Collecting requests<3.0.0,>=2.16.0
  Using cached requests-2.24.0-py2.py3-none-any.whl (61 kB)
Requirement already satisfied: eth-hash[pycryptodome]<1.0.0,>=0.2.0 in c:\python38\lib\site-packages (from web3) (0.2.0)
Requirement already satisfied: pypiwin32>=223; platform_system == "Windows" in c:\python38\lib\site-packages (from web3) (223)
Collecting eth-utils<2.0.0,>=1.8.4
  Using cached eth_utils-1.9.0-py3-none-any.whl (24 kB)
Collecting parsimonious<0.9.0,>=0.8.0
  Using cached parsimonious-0.8.1.tar.gz (45 kB)
Collecting eth-keyfile<0.6.0,>=0.5.0
  Using cached eth_keyfile-0.5.1-py3-none-any.whl (8.3 kB)
Collecting rlp<2,>=1.0.0
  Using cached rlp-1.2.0-py2.py3-none-any.whl (19 kB)
Collecting bitarray<1.3.0,>=1.2.1
  Using cached bitarray-1.2.2.tar.gz (48 kB)
Collecting eth-keys!=0.3.2,<0.4.0,>=0.2.1
  Using cached eth_keys-0.3.3-py3-none-any.whl (20 kB)
Collecting eth-rlp<1,>=0.1.2
  Using cached eth_rlp-0.1.2-py3-none-any.whl (6.5 kB)
Collecting multiaddr>=0.0.7
  Using cached multiaddr-0.0.9-py2.py3-none-any.whl (16 kB)
Requirement already satisfied: six>=1.9 in c:\python38\lib\site-packages (from protobuf<4,>=3.10.0->web3) (1.15.0)
Requirement already satisfied: setuptools in c:\python38\lib\site-packages (from protobuf<4,>=3.10.0->web3) (41.2.0)
Requirement already satisfied: attrs>=17.4.0 in c:\python38\lib\site-packages (from jsonschema<4.0.0,>=3.2.0->web3) (19.3.0)
Requirement already satisfied: pyrsistent>=0.14.0 in c:\python38\lib\site-packages (from jsonschema<4.0.0,>=3.2.0->web3) (0.16.0)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Using cached urllib3-1.25.10-py2.py3-none-any.whl (127 kB)
Collecting chardet<4,>=3.0.2
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2020.6.20-py2.py3-none-any.whl (156 kB)
Requirement already satisfied: pycryptodome<4,>=3.6.6; extra == "pycryptodome" in c:\python38\lib\site-packages (from eth-hash[pycryptodome]<1.0.0,>=0.2.0->web3) (3.9.8)
Requirement already satisfied: pywin32>=223 in c:\python38\lib\site-packages (from pypiwin32>=223; platform_system == "Windows"->web3) (228)
Collecting cytoolz<1.0.0,>=0.10.1; implementation_name == "cpython"
  Using cached cytoolz-0.10.1.tar.gz (475 kB)
Collecting netaddr
  Using cached netaddr-0.8.0-py2.py3-none-any.whl (1.9 MB)
Collecting base58
  Using cached base58-2.0.1-py3-none-any.whl (4.3 kB)
Collecting varint
  Using cached varint-1.0.2.tar.gz (1.9 kB)
Requirement already satisfied: toolz>=0.8.0 in c:\python38\lib\site-packages (from cytoolz<1.0.0,>=0.10.1; implementation_name == "cpython"->eth-utils<2.0.0,>=1.8.4->web3) (0.10.0)
Using legacy 'setup.py install' for lru-dict, since package 'wheel' is not installed.
Using legacy 'setup.py install' for parsimonious, since package 'wheel' is not installed.
Using legacy 'setup.py install' for bitarray, since package 'wheel' is not installed.
Using legacy 'setup.py install' for cytoolz, since package 'wheel' is not installed.
Using legacy 'setup.py install' for varint, since package 'wheel' is not installed.
Installing collected packages: cytoolz, eth-utils, parsimonious, eth-abi, eth-keys, eth-keyfile, hexbytes, rlp, bitarray, eth-rlp, eth-account, netaddr, base58, varint, multiaddr, idna, urllib3, chardet, certifi, requests, ipfshttpclient, protobuf, lru-dict, web3
    Running setup.py install for cytoolz ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Windows\\Temp\\pip-install-1c5kaiox\\cytoolz\\setup.py'"'"'; __file__='"'"'C:\\Windows\\Temp\\pip-install-1c5kaiox\\cytoolz\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Windows\Temp\pip-record-u698xvml\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\python38\Include\cytoolz'
         cwd: C:\Windows\Temp\pip-install-1c5kaiox\cytoolz\
    Complete output (56 lines):
    ALERT: Cython not installed.  Building without Cython.
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.8
    creating build\lib.win-amd64-3.8\cytoolz
    copying cytoolz\compatibility.py -> build\lib.win-amd64-3.8\cytoolz
    copying cytoolz\utils_test.py -> build\lib.win-amd64-3.8\cytoolz
    copying cytoolz\_signatures.py -> build\lib.win-amd64-3.8\cytoolz
    copying cytoolz\_version.py -> build\lib.win-amd64-3.8\cytoolz
    copying cytoolz\__init__.py -> build\lib.win-amd64-3.8\cytoolz
    creating build\lib.win-amd64-3.8\cytoolz\curried
    copying cytoolz\curried\exceptions.py -> build\lib.win-amd64-3.8\cytoolz\curried
    copying cytoolz\curried\operator.py -> build\lib.win-amd64-3.8\cytoolz\curried
    copying cytoolz\curried\__init__.py -> build\lib.win-amd64-3.8\cytoolz\curried
    copying cytoolz\dicttoolz.pyx -> build\lib.win-amd64-3.8\cytoolz
    copying cytoolz\functoolz.pyx -> build\lib.win-amd64-3.8\cytoolz
    copying cytoolz\itertoolz.pyx -> build\lib.win-amd64-3.8\cytoolz
    copying cytoolz\recipes.pyx -> build\lib.win-amd64-3.8\cytoolz
    copying cytoolz\utils.pyx -> build\lib.win-amd64-3.8\cytoolz
    copying cytoolz\cpython.pxd -> build\lib.win-amd64-3.8\cytoolz
    copying cytoolz\dicttoolz.pxd -> build\lib.win-amd64-3.8\cytoolz
    copying cytoolz\functoolz.pxd -> build\lib.win-amd64-3.8\cytoolz
    copying cytoolz\itertoolz.pxd -> build\lib.win-amd64-3.8\cytoolz
    copying cytoolz\recipes.pxd -> build\lib.win-amd64-3.8\cytoolz
    copying cytoolz\utils.pxd -> build\lib.win-amd64-3.8\cytoolz
    copying cytoolz\__init__.pxd -> build\lib.win-amd64-3.8\cytoolz
    creating build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\dev_skip_test.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_compatibility.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_curried.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_curried_toolzlike.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_dev_skip_test.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_dicttoolz.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_docstrings.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_doctests.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_embedded_sigs.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_functoolz.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_inspect_args.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_itertoolz.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_none_safe.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_recipes.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_serialization.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_signatures.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_tlz.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_utils.py -> build\lib.win-amd64-3.8\cytoolz\tests
    running build_ext
    building 'cytoolz.dicttoolz' extension
    creating build\temp.win-amd64-3.8
    creating build\temp.win-amd64-3.8\Release
    creating build\temp.win-amd64-3.8\Release\cytoolz
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\python38\include -Ic:\python38\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include" /Tccytoolz/dicttoolz.c /Fobuild\temp.win-amd64-3.8\Release\cytoolz/dicttoolz.obj
    dicttoolz.c
    c:\python38\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.24.28314\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Windows\\Temp\\pip-install-1c5kaiox\\cytoolz\\setup.py'"'"'; __file__='"'"'C:\\Windows\\Temp\\pip-install-1c5kaiox\\cytoolz\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Windows\Temp\pip-record-u698xvml\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\python38\Include\cytoolz' Check the logs for full command output.

i don't understand what wrong in this code when I execute 

"pip install web3"

**Comment by kclowes** [comment]
@xerx-x does installing Microsoft Visual Studio as mentioned [above](https://github.com/ethereum/web3.py/issues/1578#issuecomment-585292341) work? If not, there are some answers here that might help: https://stackoverflow.com/questions/40018405/cannot-open-include-file-io-h-no-such-file-or-directory. If neither of those fix the problem, feel free to open a new issue.

**Comment by takipsizad** [comment]
uhhh

**Comment by mhmehdi** [comment]
I have the same problem and I couldn't find a solution even tried [this](https://aka.ms/vs/16/release/VC_redist.x64.exe)

**Comment by vkage** [comment]
Hi i found solution after trying these steps..


For this error
```
 copying cytoolz\tests\test_tlz.py -> build\lib.win32-3.8\cytoolz\tests
    copying cytoolz\tests\test_utils.py -> build\lib.win32-3.8\cytoolz\tests
    running build_ext
    building 'cytoolz.dicttoolz' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\lenovo\hamada\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\LENOVO\\AppData\\Local\\Temp\\pip-install-y6c8xmww\\cytoolz\\setup.py'"'"'; __file__='"'"'C:\\Users\\LENOVO\\AppData\\Local\\Temp\\pip-install-y6c8xmww\\cytoolz\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\LENOVO\AppData\Local\Temp\pip-record-dphc6qzi\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\lenovo\hamada\include\site\python3.8\cytoolz' Check the logs for full command output.
>
```

Download latest > [Microsoft C++ Build Tools](https://visualstudio.microsoft.com/visual-cpp-build-tools/)

Select tools as shown in screenshot >

![image](https://user-images.githubusercontent.com/32420145/147341720-f66a5cc1-63b6-479f-b8c2-719a704cd17b.png)

After this you will get error like this ..
```
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Users\VIVEKK4\AppData\Local\Programs\Python\Python39\libs /LIBPATH:C:\Users\VIVEKK4\AppData\Local\Programs\Python\Python39\PCbuild\amd64 /LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64 /LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.20348.0\ucrt\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.20348.0\um\x64 /EXPORT:PyInit_dicttoolz build\temp.win-amd64-3.9\Release\cytoolz/dicttoolz.obj /OUT:build\lib.win-amd64-3.9\cytoolz\dicttoolz.cp39-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.9\Release\cytoolz\dicttoolz.cp39-win_amd64.lib
    dicttoolz.obj : warning LNK4197: export 'PyInit_dicttoolz' specified multiple times; using first specification
       Creating library build\temp.win-amd64-3.9\Release\cytoolz\dicttoolz.cp39-win_amd64.lib and object build\temp.win-amd64-3.9\Release\cytoolz\dicttoolz.cp39-win_amd64.exp
    Generating code
    Finished generating code
    LINK : fatal error LNK1158: cannot run 'rc.exe'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit code 1158
```

Resolution 

Add this to your PATH environment variables:
```
C:\Program Files (x86)\Windows Kits\10[8.0]\bin\x64[x86]
```
Copy these files:
```
rc.exe
rcdll.dll
```

From
```
C:\Program Files (x86)\Windows Kits\10\bin\10.0.20348.0\x86
```
To
```
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin
```

now run 
```
pip install web3
```
Done! 
--------------------

For Reference stackoverflow links >

- [link1](https://stackoverflow.com/questions/40018405/cannot-open-include-file-io-h-no-such-file-or-directory)
- [link2](https://stackoverflow.com/questions/43858836/python-installing-clarifai-vs14-0-link-exe-failed-with-exit-status-1158)
- [link3](https://stackoverflow.com/questions/14372706/visual-studio-cant-build-due-to-rc-exe?newreg=f00ac10c2a4448ceb438f258e5c229a4)
