### ISSUE TITLE
ENS.fromWeb3 not copying middleware

### ISSUE THREAD

**Issue by Uxio0** [ethereum/web3.py#1657]
* Version: 5.10.0
* Python: 3.8
* OS: linux

### What was wrong?

I would expect that after configuring a Web3 instance, if I do `ENS.fromWeb3(w3)` it would copy the middleware and parameters needed. Instead, it just uses the provider. This is very important for using ENS with Rinkeby and Geth, as it needs the POA middleware.

Steps to reproduce:

Initialize instance of Web3, add middleware for POA and then create an ENS instance from that.

### How can it be fixed?

Copy web3 instance or allow to provide one.

**Comment by marcgarreau** [comment]
Thanks for the report. Seems like a reasonable expectation. 

I see that `fromWeb3` just [peels the provider](https://github.com/ethereum/web3.py/blob/master/ens/main.py#L102) off of the web3 instance passed in, because ENS accepts a provider. Upon creation, there's also some [adding and removing of middleware](https://github.com/ethereum/web3.py/blob/master/ens/utils.py#L91-L95) as a result of the `init_web3` method.

@pipermerriam @carver thoughts on passing/cloning a web3 instance into ENS to preserve middleware onion? Was this avoided in the past for any reason? If you like the idea, do you have a preferred implementation?

**Comment by carver** [comment]
Yeah, there are definitely some quirks there. But I *think* they're all managed by the methods @marcgarreau  already found at https://github.com/ethereum/web3.py/blob/6258d2e1c807aee892481296c7f115399ce6a6f8/ens/utils.py#L77-L96

So the bulk of the work is to pass in a "template" w3 instance and copy the existing middlewares & provider, as a kind of alternative to `init_web3()`, then apply `customize_web3()`

(Also a reminder that @Uxio0 will have to pass `addr` into `ENS.fromWeb3()` for non-mainnet usage, since ENS is hosted at a different addresses on different networks IIRC)
