### ISSUE TITLE
Update Geth Version Support

### ISSUE THREAD

**Issue by kclowes** [ethereum/web3.py#1703]
This can probably be split up into two related issues, but since the Geth team doesn't support any old versions, we can at least drop support for Geth versions prior to the most recent hard fork. Dropping support includes: 
- removing logic around the old versions in integration tests 
- updating the integration test fixture to the most recent Geth and then fixing any broken tests
   - We will probably also need to add the most recent Geth version(s) to py-geth
- Making sure we have all breaking changes accounted for since 1.9.7

**Comment by marcgarreau** [comment]
Geth version was bumped to 1.9.19 in this PR: https://github.com/ethereum/web3.py/pull/1708. A couple patch releases have come out since, but the purpose of this issue has been achieved. (Bumping to the latest version will cause all Whisper-related tests to fail. This has been noted in the v6 breaking changes list.)
