### ISSUE TITLE
Get the contract abi by address to simplify contract constructor? [FEATURE]

### ISSUE THREAD

**Issue by hivemall** [ethereum/web3.py#1711]
Reviewing the [doc](https://web3py.readthedocs.io/en/latest/examples.html#sending-tokens) it seems not possible to send/receive erc20s since the contract `>>> contract = w3.eth.contract(contract_address, abi=ABI)` expects an abi to be avail (eg from https://etherscan.io/address/0x0f5d2fb29fb7d3cfee444a200298f468908cc942#code).

Expected: The contract address should suffice as unique identifier pulling the contracts abi/bytecode directly from the chain making the send/receive a charm. Constructor only takes contract address.
 Is this looked into?

**Comment by marcgarreau** [comment]
This feels like a layer on top of web3.py to me. The change would be fairly significant, requiring a round trip to a node or external service for lookup. If you have some need of dynamic ABI lookups, I think it would be relatively straightforward to build that functionality yourself and be able to more easily account for where to do the lookup, what chain you're on, etc. Otherwise, if you're making repeated use of a single contract, typically you look it up once and you're done.

@hivemall do you have some specific use case in mind or just like the idea of the convenience?

**Comment by hivemall** [comment]
i was browsing around myetherwallet and noticed that they pull it from their github repo  [const fetchContracts = async () => {](https://github.com/MyEtherWallet/MyEtherWallet/blob/8616f0847d70bd23e4c27db40294f86c4c01bc81/fetchLists/index.js#L167), thats all. 
on top or middleware layer is probably way to go. ty
