### ISSUE TITLE
How do I count the elements of an array in solidity?

### ISSUE THREAD

**Issue by duaa99** [ethereum/web3.py#1723]
In my project, I want to count the elements of an array as follows:

 ```
   struct Server{
    
       uint sernum;
       uint num;
       uint data;
    }
    Server [] public datta;


    
    function count() public constant returns(uint sercount) {
        
        return datta.length;
    }
    function set_data (uint Sernum ,uint Num, uint Data  ) public  {
        Server memory xserver = Server(Sernum,Num,Data);
        uint x= count();
        bool y;
        if(x>=1){
            
            for (uint i = 0; i<datta.length;i++){
            
                if(datta[i].sernum == Sernum && datta[i].num==Num && datta[i].data<Data){
                    
                    y=true;
                }
                else{
                    
                    y==false;
                }
            }
            if (y==true){
              
                datta.push(xserver);
      }
   }
```
When I call a count function to see how many elements in the array it always gives me 1 no matter how many of the elements of the array

`   print( format(contract.functions.count().call()))
`How do I count the elements of an array ??

**Comment by kclowes** [comment]
It looks like there is something wrong with your Solidity code. I am going to close because this looks to me like more of a Solidity question than a web3 question but feel free to reopen if you feel that I'm wrong. I would start debugging by using [Remix](remix.ethereum.org) to compile your Solidity and then you can deploy a contract to the testnet and interact with it that way all through Remix. [This](https://www.dappuniversity.com/articles/solidity-tutorial) looks like a decent tutorial at quick glance, although the layout of Remix has changed since it was written so some of the buttons might be in a different place.
