### ISSUE TITLE
Interest/feasibility of "headless" Contract instances? Overview/discussion inside...

### ISSUE THREAD

**Issue by elliottdehn** [ethereum/web3.py#1819]
* Version: 5.13.1
* Python: 3.9
* OS: osx
* `pip freeze` output:

```
astroid==2.4.2
attrs==20.3.0
autopep8==1.5.4
base58==2.0.1
bitarray==1.2.2
cachetools==4.2.0
certifi==2020.12.5
chardet==4.0.0
colorful==0.5.4
cytoolz==0.11.0
depq==1.5.5
eth-abi==2.1.1
eth-account==0.5.4
eth-hash==0.2.0
eth-keyfile==0.5.1
eth-keys==0.3.3
eth-rlp==0.2.1
eth-typing==2.2.2
eth-utils==1.9.5
hexbytes==0.2.1
idna==2.10
ipfshttpclient==0.7.0a1
isort==5.6.4
jsonschema==3.2.0
lazy-object-proxy==1.4.3
lru-dict==1.1.6
mccabe==0.6.1
multiaddr==0.0.9
netaddr==0.8.0
parsimonious==0.8.1
prettyprinter==0.18.0
protobuf==3.14.0
pycodestyle==2.6.0
pycryptodome==3.9.9
Pygments==2.7.3
pylint==2.6.0
pyrsistent==0.17.3
readerwriterlock==1.0.7
requests==2.25.1
rlp==2.0.1
rope==0.18.0
six==1.15.0
termcolor==1.1.0
toml==0.10.2
toolz==0.11.1
typing-extensions==3.7.4.3
urllib3==1.26.2
varint==1.0.2
web3==5.13.1
websockets==8.1
wrapt==1.12.1
```

### What was wrong?

**In general:** Instances of Contracts in web3py seem to retain/depend on the Web3 instance and connection that was used to create them. While this is somewhat convenient for "total encapsulation," it causes problems for WebSocket connections in particular. Unlike HTTP-based Web3 instances, WebSocket instances don't seem to support multi-threaded usage, even remotely, in any capacity.

**What this means:** In applications requiring _very many_ different instances of Contracts across many threads and processes (where the performance improvements of WebSockets over HTTP is a functional requirement) you have a couple of options, none of which are ideal.

**Some existing approaches:**

- Re-create the requisite contract instance every time it is needed using a "free/available" Web3 instance (i.e use a Queue as a sort of "connection pool")

**Problems:** From my testing, creating a Contract instance takes roughly 15 milliseconds. This is a significant overhead for a request which can range up to about 5-8ms execution time. This overhead is so great that using HTTP connections may out-compete this approach.

- Give each Contract instance its own dedicated WebSocket connection

**Problems:** Holding open a significant number of long-lived connections, in general, isn't ideal. One of the risks here is significant performance issues caused by the different connections "thrashing" for CPU time when too many are in use at once. Ideally, one can strictly upper-bound the number of connections in simultaneous use by creating strictly the number of desired Web3 instances/connections. Having a strict upper-bound reduces the need to carefully consider Web3 instance usage all throughout a many-threaded application.

In my testing, having too many connections in _concurrent_ use (i.e hyper-threaded and/or multi-processed) to a node running locally can increase request execution time by over 50x. My requests went from ~5ms to over ~250ms... the optimal number of connections seems to be about 1-per-logical-thread. Top-of-the-line available hardware has 128 logical threads, while personal hardware tends to have about 8. This assumes the CPU has hyper-threading support, most of which do nowadays.

- Distribute the Contract instances over the Web3 instances and use a specialized structure to provide the desired Contract instance once the connection it depends on becomes available

This can become messy and subtle, and creates an arbitrarily-high upper bound for how long a thread may wait for a connection as many threads may simultaneously demand contracts, all just-so-happening to depend on the same connection.

### How can it be fixed?

Create a special type of _"headless"_ Contract instance to which one can provide a Web3 instance at _creation_ time, but after which the instance is "forgotten" in favor of requiring a Web3 instance to be provided _at the moment of each request._ This may look something like so:

`contract.functions.someReadOnlyFunction(w3 instance)(otherwise identical API)`

This would allow one to use the simple and intuitive approach of using a Queue to buffer the set of Web3 connections, while still allowing for all of the desired contract instances to be created just once and re-used from there on. The API of the Contract instances would be 100% identical outside of the need to supply a Web3 connection for operations.

It would perhaps be wise to require a supplied instance even for operations which don't require one presently. This would be because present usage of the current Contract API generally just assumes a connection is available for all operations. Requiring a Web3 instance for all operations therefore captures the semantic behavior encapsulated by the other instance types.

Alternatively, perhaps this Contract type could require a "Web3 supplier," which implements a specific API, at creation time. From thereon, it would get its required Web3 connections from said supplier. Regardless: the desired behavior is a Contract instance which can be _efficiently_ accessed and re-used by multiple threads without the many issues caused by the Contract using just one connection.

Similar to that approach would be to have a special Web3 Provider which implements the Provider API, but internally uses a buffer of n-many other providers. Perhaps call it `Web3.MultiProvider`. This would make it so no new Contract type is needed, as the provider could be passed around and used just like any other provider.

**Other notes:**
For this particular Contract instance type, it may also be wise to have explicit, first-class support for multithreaded use cases. I'm not certain, but it may be possible to actually pickle this type of contract as well? That would be great, as instances could then be passed into spawned processes rather than requiring mass re-creation by the new process.

**What do people make of this? Is there interest?** Perhaps there is an approach that I'm missing which would accomplish what I desire here. Discussion would be appreciated!

**Comment by kclowes** [comment]
Thank you for such a detailed issue! Without digging in too much, I think a "headless" contract like you outlined above: (`contract.functions.someReadOnlyFunction(w3 instance)(otherwise identical API)`) is feasible, but would be a significant change to the codebase. To restate the problem you're having: it seems like it's hard to work with many different contracts because of bottlenecks at the provider level - does that sound right? And if that's the case, it seems like it _may_ be better to address that on the provider level (and maybe the highest priority is the WebsocketProvider), rather than mucking around with the API for `contract`. We are working toward an async version of each provider, so I wonder how much that would help this use case. If that doesn't end up helping enough, the `MultiProvider` might be a good first step, and maybe we could even add a feature where a user could add their own logic for which provider to pick.

@pipermerriam I'd love to get your thoughts here when you get a chance!

**Comment by pipermerriam** [comment]
I'm not sure the change would have to be significant.

https://github.com/ethereum/web3.py/blob/dd35bbc23904addacd032855059af5dfba691bc6/web3/contract.py#L955

If `ContractFunction.call(...)` took an optional web3 instance it would be easy to use that **if** provided, and fall back to the `self.web3` otherwise.

I'm sure there's a bunch of hidden complexity though:

- Still no way to fully detatch the contract from the web3 instance without more API changes...  so that's a bit of a footgun since you would need to do something gross like create it with one and then be **really** careful.  Icky.
- Probably lots of places where `self.web3` gets used that are buried down in the various calls. Someone would need to attempt making this change and see whether this is an issue.

I think it's probably possible to fundamentally adjust how we do things without actually breaking the existing API.  Off the top of my head we would want:

#### Contract factories to be fully decoupled from the Web3 instance.

```python
# lowest level primative
from web3 import create_contract_factory

Factory = create_contract_factory(abi=..., ???)
```

Decoupling factory creation from the web3 instance looks very doable without breaking any major APIs

#### Decoupling contract interactions from the web3 instance

Currently, the contract instances *expect* to have a handle to a `w3` object.

If we wanted to do this right, then we would want to break that assumption so that the `w3` object is explicitely passed along through the call so as to eliminate the "foot gun".  The goal here would be to have both ways of interacting with the contract go through the same code paths.

1. low level API that explicitely passes the `w3` object around
2. high level API (what people use today) that just wraps the low level API.

I don't know the exact shape of this but today it looks roughly like this:

- Make the factory (bind to w3 happens here)
- Make the instance of the factory bound to an address
- Access the function/event/whatever and call it.
    - internals do all the encoding/decoding/etc

After this change it would look roughly like this

- Make the factory (NOT bound to w3)
- Make the instance (binds to w3)
- Access the function/event/whatever and call it
    - Lookup of function/event uses class-level APIs that are not bound to w3
    - Function/Event "prepares" the call, still not bound to w3
    - Actual call is made, binding to the w3 instance at this stage, getting a "raw" response.
    - Result is decoded by the Function/Event, ideally not bound to w3
    - result returned to user

In theory, some psuedo code of the above done manually would look like:

```python
# traditional
Factory = create_contract_factory(...)
contract = Factory(address, w3)
result = contract.functions.myFunc(...).call(...)

# headless
Factory = create_contract_factory(...)
prepared_call = Factory.functions.myFunc(...).prepare_call()
call_txn = prepared_call.build_transaction(w3)
raw_result = w3.eth.call(call_txn)
result = prepared_call.parse_result(w3, raw_result)
```

The "traditional" approach from above would simply be doing the "headless" thing under the hood....

I have no idea if this is a good idea.  It's more layers of abstraction to an already complex/abstraction-heavy thing, but it also might be a wonderful thing to place strict bounds on where the `w3` API surface area is actually being exposed.

**Comment by pacrob** [comment]
This hasn't been bumped for a few years, closing as stale.
