### ISSUE TITLE
Support for EIP-1559

### ISSUE THREAD

**Issue by kclowes** [ethereum/web3.py#1835]
* Version: v5.14+

### What was wrong?
It looks like [EIP-1559](https://eips.ethereum.org/EIPS/eip-1559) is coming up soon (maybe in the London hard fork), so we'll need to update web3py to support it. This is a placeholder issue that will likely get broken down into a few issues. 

### How can it be fixed?
From a high level, it looks like we need to change our transaction object:
- New fields in the transaction:
    - fee_cap_per_gas
    - max_miner_bribe_per_gas
- ~Remove gas_price (will probably need to keep it in in v5 and then need to make a note to remove in v6)~

BlockData will need to change as well:
- Add base_fee field
- ~move gas_limit to gas_target (In v5, we'll need to keep both gas_limit and gas_target and remove gas_limit in v6).~ 

Also probably simplifies (possibly removes the need for) our gas price strategies.

@abdelhamidbakhta or @pipermerriam let me know if I'm missing anything!

**Comment by abdelhamidbakhta** [comment]
@kclowes Thank you very much for starting looking at this. 
You don't have to remove `gas_price`. There is no plan/timeline to remove legacy transaction support for the moment.  @timbeiko can you confirm ?
Also IMO the `move gas_limit to gas_target` is not necessary. It is a nice to have though.
Otherwise the high level approach makes a lot of sense.

**Comment by timbeiko** [comment]
No plan on removing legacy transactions in the foreseeable future!

**Comment by kclowes** [comment]
There are a few issues open that still need some work, but initial MVP work on 1559 support has been completed. See #2065 and #2066.
