### ISSUE TITLE
 ValueError: {'code': -32000, 'message': 'filter not found'} while fetching events using .get_all_entries() . 

### ISSUE THREAD

**Issue by gitpull2** [ethereum/web3.py#1840]
node (BSC mainnet): "https://bsc-dataseed.binance.org/ 

Error message - 
```
ValueError: {'code': -32000, 'message': 'filter not found'}
```

Code -
```
contractCreate = w3.eth.contract(address=contractaddress, abi=abiSMC)
FilteredEvents= contract.events.Transfer.createFilter(fromBlock= startingBlock,toBlock=w3.eth.blockNumber)
print(FilteredEvents.get_all_entries())
```
Error shows up at `print `statement 

Error arbitarily shows up . It is more frequent if `startingBlock `is a small value . Sometimes there is no error and data is recieved smoothly. 
Why is this error showing ? Can this code be used in production given the arbitariness with which the error is showing ?How do I correct the code ?

**Comment by kclowes** [comment]
I'm not sure about BSC mainnet, but filters are notoriously flaky on mainnet nodes. Your error message looks like the node dropped the filter which sometimes happens if too much time passes, or if there are too many records in a request. Last I checked on mainnet, 50 blocks was about the most blocks you could do, but not sure how that translates to your node/chain. You may try using [local_filter_middleware](https://web3py.readthedocs.io/en/stable/middleware.html#locally-managed-log-and-block-filters) also. I'm going to close since it doesn't look like this is a web3py issue, but feel free to reopen if you think that's wrong. Thanks!
