### ISSUE TITLE
Enable strict byte length checking by default

### ISSUE THREAD

**Issue by kclowes** [ethereum/web3.py#1903]
* Version: v6

### What was wrong?

In v5, there is a flag where you can enable strict bytes length checking. See [these docs](https://web3py.readthedocs.io/en/latest/contracts.html#enabling-strict-checks-for-bytes-types) for some background. We want to remove the flag and make the strict checking the default. 

### How can it be fixed?

[This PR](https://github.com/ethereum/web3.py/pull/1419) added the flag and the stricter checks. We may want to keep flexible bytes type checking and put that behind the flag instead.

**Comment by benber86** [comment]
I started working on this and have a question: since the strict byte length checking is going to be the default behavior, should variables named to indicate a strict behavior be renamed accordingly?

For instance in the tests, things like `StrictArraysContract` would become `ArraysContract` and the old `ArraysContract` would be renamed to something like `NonStrictArraysContract` ?

On Discord, @marcgarreau suggested making names explicit in both cases with `Strict` and `NonStrict`, which could potentially mean renaming all variables for default behavior to indicate `Strict` even if they are not always used to test for strict mode behavior. For instance the `web3` fixture used for all testing would need be renamed to `web3_strict`. Likewise the `ArraysContract` would be renamed to `StrictArraysContract` even though it's also used by several test functions that do not test for strict mode.
