### ISSUE TITLE
Failed to get token balance

### ISSUE THREAD

**Issue by notooth1** [ethereum/web3.py#1912]
I failed to get the balance of tokens with this code. Can anyone help me fix it?

```
abi = json.loads('[{"constant":true,"inputs":[],...}]')
contractAddress = "0xDef1C0ded9bec7F1a1670819833240f027b25EfF"
accountAddress = "0x55C18A6D97E738d27b29ecD7018e04ef2da8Ff0a"
contract = w3.eth.contract(address=contractAddress, abi=abi)
balance  = contract.functions.balanceOf(accountAddress).call()
```

Error:

`web3.exceptions.ContractLogicError: execution reverted`

**Comment by marcgarreau** [comment]
@notooth1 did you get this sorted out? On quick glance, the ABI can be input as a string rather than json. Other than that, the snippet looks fine. More code/exception messaging would be required to properly diagnose. However, this sort of question is best asked in stack overflow or in the Discord server (invite link in the README).
