### ISSUE TITLE
ValueError: {'code': -32601, 'message': 'The method eth_sendTransaction does not exist/is not available'}

### ISSUE THREAD

**Issue by rjbanna** [ethereum/web3.py#1995]
I'm getting above error while trying to deploy contract using
`my_contract.constructor().transact()`

When I tried to run same using ganache GUI, it's giving me following error
`web3.exceptions.ContractLogicError: execution reverted: VM Exception while processing transaction: revert`

This is because of gas_estimate failed. I don't know how to fund contract with eth to cover gas fees. My account has enough eth available to deploy the contract. If anybody has example for this, please share.

I'm using Python 3.7 with latest web3.py version and Infura Kovan.

**Comment by marcgarreau** [comment]
The error occurs because Infura cannot interact with your local private key, by design. You'll have to build, sign, and send a raw transaction instead. See [this example](https://web3py.readthedocs.io/en/stable/web3.eth.account.html#sign-a-contract-transaction), replacing `transfer` in the example with `constructor` to deploy. Start from the top of that page to learn the differences in private and hosted key management within Web3.py. Reopen if that doesn't address your issue.
