### ISSUE TITLE
`BuildTransaction` and `estimateGas` launch the transaction and caus a revert.

### ISSUE THREAD

**Issue by moda20** [ethereum/web3.py#2041]
* Version: latest
* Python: 3.6
* OS: osx

### What was wrong?

i am trying to estimate the gas of a contract function, and when add .estimateGasAfter my contract method name, i find out that it launches the transaction, reverts and causes my script to fail as if the actual transaction reverted. 

```
smartContract.functions.executeMethod(....).estimateGas({'from': account.address})
```
the line above would launch the transaction without even going through the signing process and it will revert and causes an error in my script. if i put that call in a try/except block it will continue down the lines and the same thing would happen with the transaction building line (`buildTransaction`).

**Comment by kclowes** [comment]
I think this means that the transaction will revert based on what you're passing in because some contract logic isn't being fulfilled. I'd double check the parameters you're passing, and try again. I'm going to close because I don't think this is an issue with the library, but feel free to reopen if you think that's wrong!

**Comment by moda20** [comment]
yes, the method will revert, and that is expected in this case. the issue i have is that `buildTransaction` for example is a local function that doesn't call any rpc method of my node and would only reformat the data it has into a transaction dictionary but in my case, it does run the method as if it is sending a transaction. it doesn't return a transaction dict but rather literally run the function. and that, i think, is not the desired behavior.

**Comment by josh-gree** [comment]
Perhaps I am completely missing something but I understood this to be an `offline` method? However calling buildTransaction does in fact result in an rpc call to the node - why is this?

**Comment by fselmo** [comment]
@josh-gree If you do not pass in a gas price to the transaction, for example, there will indeed be an RPC call to `eth_estimateGas` in order to build a dict for you with an appropriate value. This is not the same as sending a transaction. I imagine that is the call you are seeing? If not can you provide more context?
