### ISSUE TITLE
Feature Request: Websocket Pool

### ISSUE THREAD

**Issue by freaker2k7** [ethereum/web3.py#2090]
Version: latest
Python: any
OS: osx/linux

```
pip output irrelevant
```

### Problem with concurrent connections

I'm using the threading (pool) library in my code.
When there're several parallel requests to my local ("fast" synced) node, I get:

```
RuntimeError: cannot call recv while another coroutine is already waiting for the next message
```

### Let's do a pool :)

Following [when "cannot call recv while another coroutine is already waiting for the next message" will happen](https://github.com/aaugustin/websockets/issues/862) & [What is the right way to recv responses?](https://github.com/aaugustin/websockets/issues/807) I have a suggestion to create a Websocket Pool like [ws4py](https://ws4py.readthedocs.io/en/latest/sources/managertutorial/)

I tried looking at [websocket.py](https://github.com/ethereum/web3.py/blob/master/web3/providers/websocket.py) but it uses a different Websocket client than [ws4py's client](https://github.com/Lawouach/WebSocket-for-Python/blob/master/ws4py/client/__init__.py).
I didn't want to tweak anything yet, because I wanted to consult with the community.

I think the [WebsocketProvider](https://github.com/ethereum/web3.py/blob/master/web3/providers/websocket.py#L88) class can be renamed to WebsocketSingleProvider and wrapped in the new WebsocketProvider which will implement a pool of WebsocketSingleProvider's. The pool limit can be the minimum of the concurrent requests and some MAX_WEBSOCKET_CONNECTIONS which can be set to something safe and round like 256.

```
MAX_WEBSOCKET_CONNECTIONS = 256
...
current_loop_queue_size = WebsocketProvider.requests_queue.qsize() # from queue import Queue
current_loop_pool_size = min(current_loop_queue_size, MAX_WEBSOCKET_CONNECTIONS)
```

Then (every loop) to iterate over the queue (popping requests from it) and sending them asynchronously to different connections (if exist, or create new ones, i.e. lazy loading). 
<br>

**Comment by savvn001** [comment]
Did you ever write a solution for this? I'm in the same boat and have an app where it makes concurrent websocket calls from different threads, and am running into the same RuntimeError because of this. I was hoping this project would sort of 'queue' the calls when multiple are made, or something like that.

**Comment by savvn001** [comment]
Ok well if anyone's interested, I've botched together a solution using futures.ThreadPoolExecutor, which submits tasks everytime a request is made, to one of N number of WebsocketProviders which are initialized beforehand, a bit like the suggested solution. Have a bit more testing to do, but it seems to work ok so far, I've proven you can submit multiple WS requests from different threads and it seems to work.

**Comment by savvn001** [comment]
@cryptedx Sorry I missed your response. If you're still interested see the fork of this repo on my Github profile

**Comment by fselmo** [comment]
The new `WebSocketProvider` in *web3.py* `v7` beta (`WebsocketProviderV2` in *web3.py* `v6`), which is asynchronous, resolves the issue of calling `recv()` from different parts of the codebase by utilizing a single listener task for receiving messages. Since the legacy websocket provider is deprecated and there seems to be a patched fork with a solution, I'm going to close this. If there is a relevant issue for the new websocket provider, let's start a separate discussion in a new issue.
