### ISSUE TITLE
Syntax error when calling a method 'from' from class 'web3.datastructures.AttributeDict'

### ISSUE THREAD

**Issue by cryptoevrial** [ethereum/web3.py#2107]
* Version: 5.23.0
* Python: 3.6
* OS: linux
* IDE: PyCharm

**What was wrong?**

* The code which produced the error

from web3 import Web3
w3 = Web3(Web3.HTTPProvider('https://mainnet.infura.io/v3/811ec3f711634180b065f03510code'))
tx = '0xd9fea5d2eb47d9c7c35fe709eb53afca546a41d2724e84d5b24187e4b6c7382c'
print(w3.eth.get_transaction(tx).from)

* The full output of the error
File "/Users/d/PycharmProjects/web3/from_issue.py", line 4
    w3.eth.get_transaction(tx).from
                               ^
SyntaxError: invalid syntax

* What type of node you were connecting to.
Infura

**Comment by kclowes** [comment]
I think the problem is that `from` is a reserved word, so you can't call it using the dot notation. You could add some middleware to convert `from` to `_from` or something if you need to access it via dot notation, or just use the regular `tx['from']`. I'm going to close because I don't think it's worth adding this middleware/formatter to the main library, but could be convinced if you feel strongly!

**Comment by cryptoevrial** [comment]
Yes, tx['from'] doing well for me! Thank you a lot!
