### ISSUE TITLE
Any request return "Parser Error"

### ISSUE THREAD

**Issue by mr-tron** [ethereum/web3.py#2145]
* Version:5.23.1
* Python: 3.6.8/3.8.10
* OS: linux
* `pip freeze` output

```
aiohttp==3.7.4.post0
async-timeout==3.0.1
attrs==21.2.0
base58==2.1.0
bitarray==1.2.2
certifi==2021.5.30
chardet==4.0.0
charset-normalizer==2.0.4
cytoolz==0.11.0
eth-abi==2.1.1
eth-account==0.5.5
eth-hash==0.3.2
eth-keyfile==0.5.1
eth-keys==0.3.3
eth-rlp==0.2.1
eth-typing==2.2.2
eth-utils==1.10.0
hexbytes==0.2.2
idna==3.2
idna-ssl==1.1.0
importlib-metadata==4.8.1
importlib-resources==5.2.2
ipfshttpclient==0.8.0a2
jsonschema==3.2.0
lru-dict==1.1.7
more-itertools==8.8.0
multiaddr==0.0.9
multidict==5.1.0
netaddr==0.8.0
packaging==21.0
parsimonious==0.8.1
protobuf==3.17.3
py-bip39-bindings==0.1.7
py-ed25519-bindings==0.1.3
py-sr25519-bindings==0.1.3
pycryptodome==3.10.1
pyparsing==2.4.7
pyrsistent==0.18.0
requests==2.26.0
rlp==2.0.1
scalecodec==0.11.19
six==1.16.0
substrate-interface==0.13.12
toolz==0.11.1
typing-extensions==3.10.0.2
urllib3==1.26.6
varint==1.0.2
web3==5.23.1
websocket-client==0.59.0
websockets==9.1
xxhash==2.0.2
yarl==1.6.3
zipp==3.5.0

```

### What was wrong?

Can't do any request to ethereum node. Server always returns "Parse Error".
```
python3
Python 3.6.8 (default, Mar 19 2021, 05:13:41) 
[GCC 8.4.1 20200928 (Red Hat 8.4.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from web3 import Web3, HTTPProvider
>>> 
>>> w3 = Web3(HTTPProvider('https://cloudflare-eth.com'))
>>> w3.isConnected()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/test/.env/lib/python3.6/site-packages/web3/main.py", line 327, in isConnected
    return self.provider.isConnected()
  File "/root/test/.env/lib/python3.6/site-packages/web3/providers/base.py", line 108, in isConnected
    assert 'error' not in response
AssertionError
```

**Comment by mr-tron** [comment]
But it works with infura - https://mainnet.infura.io/v3/
I don't know why cloudflare  returns error. It works manually via curl.
curl https://cloudflare-eth.com -H 'Content-Type: application/json' --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x1b4", true],"id":1}'

**Comment by dingguijin** [comment]
in providers/base.py
change
self.request_counter = itertools.count()
to
self.request_counter = itertools.count(start=1)

**Comment by fselmo** [comment]
@dingguijin good call on this, seems like the client may be subtracting one from the request id each time leading to a `-1` on the first call at `id=0`.

@mr-tron we'll have a change coming in soon... but for now, starting with the second request, you should be able to make successful subsequent requests because the `id` is at `1` by the second request (not ideal, see below). 

The above is not ideal so you can also do this during your setup before the first request:

```python
import itertools
from web3 import Web3, HTTPProvider

w3 = Web3(HTTPProvider('https://cloudflare-eth.com'))
w3.provider.request_counter = itertools.count(start=1)

# you can now make successful requests
```

I'm going to close this for now since I have tested this locally and it works (and should unblock you) but feel free to reopen this if this does not solve your problem and we missed something. Thanks for reporting!
