### ISSUE TITLE
construct_sign_and_send_raw_middleware uses unbuffered gas estimation following PR #1999.

### ISSUE THREAD

**Issue by ilyalesokhin-starkware** [ethereum/web3.py#2167]
After the change that made buffered gas estimate a middleware 
https://github.com/ethereum/web3.py/commit/17264b423f24a6c4e88f690391d5e9fc56bb0714
Adding the construct_sign_and_send_raw_middleware using w3.middleware_onion.add like the example
in the documentation:
https://web3py.readthedocs.io/en/stable/middleware.html#web3.middleware.construct_sign_and_send_raw_middleware
causes the signing middleware to run before the buffered gas estimate middleware and use unbuffered gas estimation that is computed here:
https://github.com/ethereum/web3.py/blob/v5.23.1/web3/_utils/transactions.py#L67

This causes sporadic out of gas failures.

injecting construct_sign_and_send_raw_middleware as the innermost middleware does not work well with the exception_retry_middleware.

**Comment by kclowes** [comment]
Thanks for raising this! Will fix!

**Comment by fselmo** [comment]
It does look like this can be fixed by encouraging injection into a layer below any transaction modifying middleware. I put up #3488 to address this. The exception retry is no longer done via middleware, instead it's a wrapper on the request functions, so that should hopefully not lead to any issues.
