### ISSUE TITLE
Send string[] as contract function input parameters

### ISSUE THREAD

**Issue by ChiHangChen** [ethereum/web3.py#2481]
* Version: 5.29.1
* Python: 3.8
* OS: Ubuntu20

HI, I have a contract funciont called `batch_mint` which accept `string[]` as input
![image](https://user-images.githubusercontent.com/22412708/169676393-5a776ec0-0c7b-4f30-8ab9-62c2038ef519.png)

I want to call it with web3.py, I tried with the following API
```
transaction = token_contract.functions.batch_mint(
    to=Web3.toChecksumAddress("0xxxxx"),
    metadata_IPFS_CIDs=["AAA", "BBB"],
).buildTransaction(
    {
        'gas': 70000,
        'gasPrice': w3.toWei('1', 'gwei'),
        'from': Web3.toChecksumAddress(my_account.address),
        'nonce': nonce
    }
) 
```
But I keep getting the error

```
ValidationError: 
Could not identify the intended function with name `batch_mint`, positional argument(s) of type `(<class 'hexbytes.main.HexBytes'>,)` and keyword argument(s) of type `{}`.
Found 1 function(s) with the name `batch_mint`: ['batch_mint(address,string[])']
Function invocation failed due to improper number of arguments.
```

How can I send the parameter input correctly?

**Comment by kclowes** [comment]
That validation error looks like it doesn't match the code you have pasted. The code looks almost right for what you're trying to do, except I'd try passing it without the keywords. So:
`token_contract.functions.batch_mint(Web3.toChecksumAddress("0xxxxx"), ["AAA", "BBB"]).buildTransaction(...)`
Closing because I don't think this is a bug, but feel free to join [our discord server](https://discord.com/invite/GHryRvPB84) and ask questions there if you still can't get it.

**Comment by ChiHangChen** [comment]
I tried without function keyword and it doesn't work either
