### ISSUE TITLE
web3.eth.estimateGas does not work properly when estimating gas cost for contract builded from abi and bytecode

### ISSUE THREAD

**Issue by Neronjust2017** [ethereum/web3.py#2508]
I have tested two situations using "web3.eth.estimateGas" to estimate the gas cost of contract transaction.

First one is to get contract by the address of a deployed contract and estimate the gas cost:

```python
mycontract = w3.eth.contract(address=mycontract_address, abi=mycontract_abi)
tx = printer.functions.fun(
    a, b, c).buildTransaction({
        'from':
        address,
        'value':
        0,
        'gasPrice':
        gasPrice,
        'gas':
        1500000,
        "nonce":
        w3.eth.getTransactionCount(address),
    })
 gasEstimate = w3.eth.estimateGas(tx)
```
The second one is to get contract by the abi and contract bytecode and estimate the gas cost:
```python
contract = w3.eth.contract(abi=abi, bytecode=bytecode)
tx = printer.functions.fun(
    a, b, c).buildTransaction({
        'from':
        address,
        'value':
        0,
        'gasPrice':
        gasPrice,
        'gas':
        1500000,
        "nonce":
        w3.eth.getTransactionCount(address),
    })
 gasEstimate = w3.eth.estimateGas(tx)
```
When the function call can be executed correctly, they both can get the estimated gas cost. However, when I pass in parameters{a,b,c} that will cause failed execution, the first situation gives the following error:
```bash
gas estimate err: {'code': -32016, 'data': 'Reverted', 'message': 'The execution failed due to an exception.'}
```
but the second gives no errors even the function execution will fail. I wonder why this could happen? How does "web3.eth.estimateGas" work?

**Comment by kclowes** [comment]
If you create a contract with just the abi and the bytecode, as in your second example, it's only a web3 object, it's not on the chain yet. If your contract is not deployed, there is no way that the client you are connecting to can know how to run your transaction.

For better or for worse, the w3.eth.contract() API will either instantiate a contract from bytecode and an abi that still needs to be deployed, and one whose address will need to be updated once it exists on-chain, or it can build you a contract object, via abi and address, that can be interacted with (ABI gives instructions on contract interaction) and also exists on chain. This means that any transaction you send can actually be processed by the client / node because they will look up what code exists at the to address from your transaction (the contract address that you provided) and now your transaction will make sense.

This code:
```python
contract = w3.eth.contract(abi=abi, bytecode=bytecode)
tx = printer.functions.fun(
    a, b, c).buildTransaction({
        'from':
        address,
        'value':
        0,
        'gasPrice':
        gasPrice,
        'gas':
        1500000,
        "nonce":
        w3.eth.getTransactionCount(address),
    })
 gasEstimate = w3.eth.estimateGas(tx)
```
will actually throw an error in web3 because it doesn't have a `to` address. But it will work as expected if you put the deployed contract address in the `to` attr.

Thanks @fselmo for getting this answer kicked off :)
