### ISSUE TITLE
dependency conflict with latest eth-account version

### ISSUE THREAD

**Issue by shaoyezh** [ethereum/web3.py#2656]
* Version: 5.31.0
* Python: 3.10
* OS: osx

The current web3 version is 5.31.0, which has a dependency on eth-account <0.5.9 , 0.6.0>. However, the latest eth-account is 0.7.0.

when using the eth-account 0.5.9 to sign an encoded struct message with type bytes, it will cause a Type error: Object of type bytes is not JSON serializable.

After I reinstall the latest eth-account 0.7.0, the error is fixed, however, this caused a dependency conflict. Could you please update the dependency?

Thanks.

**Comment by fselmo** [comment]
Hey @shaoyezh, glad you got it working. We are working on releasing web3.py `v6` which is currently in beta. Since there are breaking changes in eth-account `0.6.x` and `0.7.x`, expect to see those newer versions of eth-account in web3.py `v6`.

You can pip install the beta and give it a shot if you'd like. We will soon have a migration guide when `v6` is stable.
