### ISSUE TITLE
Importing web3 costs a lot of memory

### ISSUE THREAD

**Issue by SerK0** [ethereum/web3.py#2767]
Hi!
When I import some class from web3 lib I see that my script starting to use 25Mb.
Is it possible to decrease this amount? Is it available light weighted version?
Is it possible to import some class without importing all web3 module?

**Comment by EyalMuga** [comment]
One way to reduce memory usage is to only import the specific classes or functions that you need for your script, rather than importing the entire web3 module
 you can use a web3 light-weighted library, such as py-evm, which is a library that provides a lightweight implementation of the Ethereum virtual machine (EVM) and its associated blockchain, while still providing compatibility with the web3.py API.

**Comment by SerK0** [comment]
Thank for your answer, strangly haven't seen py-evm...
