### ISSUE TITLE
Option for turning off ```HTTPRequestRetry```

### ISSUE THREAD

**Issue by chinefed** [ethereum/web3.py#2770]
I would introduce an optional boolean parameter to turn off the ```HTTPRequestRetry``` middleware when creating a ```HTTPProvider```. This would provide users with the possibility of implementing a custom retrial logic in their code.

**Comment by kclowes** [comment]
You can just remove it and add your own. See the docs [here](https://web3py.readthedocs.io/en/v5/middleware.html?#Web3.middleware_onion.remove)

**Comment by chinefed** [comment]
I've tried to do this, but it doesn't work. Even ```w3.middleware_onion.clear()``` seems not to turn off ```HTTPRequestRetry```.  My code continues to run even if Alchemy has issued some maximum throughput error responses (I can see it from Alchemy's portal). If ```HTTPRequestRetry``` was off, the code should rise an exception and stop when receiving an error response.

```
w3 = Web3(Web3.HTTPProvider(ENDPOINT_URL))
if w3.isConnected()==False:
    print('Connection error')
w3.middleware_onion.clear()
```

**Comment by EyalMuga** [comment]
This could be due to the fact that the HTTPRequestRetry middleware is added by default to the Web3 instance when it's created, and it is not possible to remove it by using w3.middleware_onion.remove(http_retry_request_middleware).
try to create a new Web3 instance without the HTTPRequestRetry middleware, by creating your own provider class that doesn't include it.

**Comment by kclowes** [comment]
@EyalMuga you're right. The `http_retry_request_middleware` is actually on the provider, not the `middleware_onion`. So @chinefed you should be able to remove it with `w3.provider.middleware = []`. I'm going to close this, but we're going to add better UX in v7 (probably a flag on the provider).
