### ISSUE TITLE
External modules lacking type annotations

### ISSUE THREAD

**Issue by konichuvak** [ethereum/web3.py#2781]
Support for external modules has been added as of 5.29, which allows to seamlessly add new APIs to the Web3 instances.

There is, however, a lack of support for type annotations for modules. For example, if we have a following module 

```python
from web3.module import Module

class Uniswap(Module):
    def swap(self) -> bool: ...

```

we lose the type inference after attaching it to our w3 instance

```python
w3.attach_modules({"uniswap": Uniswap})
success = w3.uniswap.swap()  # type: Any
```

I am not sure how to go about adding a type annotation to a dynamically added attribute.

I guess that one could add an extra line with a type hint
```python 
w3.uniswap: Uniswap
```

but at that point it is probably simpler to just set a new attribute on the w3 instance directly

```python
w3.uniswap = Uniswap(w3)
success = w3.uniswap.swap()  # type: bool
```
which makes me wonder why would someone use modules in the first place.

**Comment by fselmo** [comment]
@konichuvak the `attach_modules()` method was just internal before. That was the only thing that changed really. You're right that python doesn't really play well with typing for dynamically added properties in this way. 

> makes me wonder why would someone use modules in the first place.

I suppose the `Module` class itself is useful if you'd like to use internal call mechanics. Perhaps the biggest question is whether or not `attach_modules()` was useful to have been made public since we lose type hinting. It may save a step or two if multiple modules are added and the type is established separately, but perhaps the documentation shouldn't put too much emphasis on _strictly_ using `attach_modules()`.

**Comment by konichuvak** [comment]
Got you, thanks for the context. Will not be using modules for now.
