### ISSUE TITLE
Remove lru-dict dependency

### ISSUE THREAD

**Issue by nlnw** [ethereum/web3.py#2884]
lru-dict requires a wheel that is not pre-compiled for Python 3.11.

It is only used in 1 place where it should be able to be replaced with the built-in functools lru cache: https://github.com/ethereum/web3.py/blob/master/web3/middleware/cache.py#L196

Removing this dependency would avoid future compatibility problems as well.

**Comment by fselmo** [comment]
Agreed. This could be cleaned up by using the internal `SimpleCache` class (as was done to the `simple_cache_middleware` when it was asynced) . I don't think this should be considered a breaking change since this would just be an implementation change for an internal cache class. I would be happy to review a PR that makes this change otherwise I can get to it sometime soon. Thanks for the issue 👍🏼

**Comment by prathmeshranaut** [comment]
Popping first item from `OrderedDict(SimpleCache)` vs `lru` cache could be considered a breaking change for some applications. 

https://github.com/ethereum/web3.py/blob/29262c9b5d4ba480d7e3d4e225448d176653d1ab/web3/utils/caching.py#L17-L29
