### ISSUE TITLE
Python for Web3 in android. Failed to install pycryptodome

### ISSUE THREAD

**Issue by Lokuslick** [ethereum/web3.py#2948]
* Python: 3.10
* OS: mac

### What was wrong?
I am using web3 in an android project. I have used com.chaquo.python package to support python in android. When I try to import web3 in a .py file I was asked to install web3. I did by using 
```
python {
            version "3.10"
            pip {
                install "web3"
            }
        }
```
When I built the project It is throwing an error to build like below.

> Failed to install pycryptodome<4,>=3.6.6; extra == "pycryptodome" from https://files.pythonhosted.org/packages/b8/2e/cf9cfd1ae6429381d3d9c14c8df79d91ae163929972f245a76058ea9d37d/pycryptodome-3.17.tar.gz#sha256=bce2e2d8e82fcf972005652371a3e8731956a0c1fbb719cc897943b3695ad91b (from eth-hash[pycryptodome]>=0.5.1->web3).

Process 'command 'python3.10'' finished with non-zero exit value 1

And exited the build.

**Comment by reedsa** [comment]
A similar issue was raised in https://github.com/chaquo/chaquopy/issues/871. In order to install pycryptodome I needed to revert to Python 3.8 and that installed pycryptodome v3.9.4 by default. 

Installing with Python >3.9 will attempt to install the latest version of pycryptodome (3.18.0). As recommended in https://github.com/chaquo/chaquopy/issues/871, you may be able to build a new version of chaquopy that installs the version of pycryptodome you need. Please raise an issue with chaquopy for their help getting that set up.

**Comment by kclowes** [comment]
Echoing what @reedsa said. Closing since this doesn't look like this is a problem with the web3 library, but a dependency resolution issue. Feel free to re-open or comment if you feel there is a problem or bug within web3. Thanks!
