### ISSUE TITLE
 cannot import name 'DEFAULT_WEBSOCKET_TIMEOUT'

### ISSUE THREAD

**Issue by viponedream** [ethereum/web3.py#3076]
ImportError: cannot import name 'DEFAULT_WEBSOCKET_TIMEOUT' from 'web3.providers.websocket' (C:\Python310\lib\site-packages\web3\providers\websocket\__init__.py)

any one know what happened?

**Comment by fselmo** [comment]
Hey @viponedream, thanks for the issue. There was only one file named `websocket.py` where these were exposed and this has since turned into a module / directory. We need to re-expose them. It should be addressed in PR #3077 and likely released in the next version of *web3.py*. Currently, the same constant is exposed via `from web3.websocket.websocket import DEFAULT_WEBSOCKET_TIMEOUT`.
