### ISSUE TITLE
web3.exceptions.TransactionNotFound:

### ISSUE THREAD

**Issue by lyc3202** [ethereum/web3.py#3155]
* Version: 6.11.0
* Python: 3.8
* OS: win
* `pip freeze` output

```
<put the output from running pip freeze here>
```

### What was wrong?

When I use the statement `w3.eth.get_transaction()` in my code, it always returns an error:
    _transaction = w3.eth.get_transaction('0x5c504ed432cb51138bcf09aa5e8a410dd4a1e204ef84bfed1be16dfba1b22060')
  File "D:\anaconda\lib\site-packages\web3\eth\eth.py", line 302, in get_transaction
    return self._get_transaction(transaction_hash)
  File "D:\anaconda\lib\site-packages\web3\module.py", line 75, in caller
    result = w3.manager.request_blocking(
  File "D:\anaconda\lib\site-packages\web3\manager.py", line 325, in request_blocking
    return self.formatted_response(
  File "D:\anaconda\lib\site-packages\web3\manager.py", line 295, in formatted_response
    apply_null_result_formatters(null_result_formatters, response, params)
  File "D:\anaconda\lib\site-packages\web3\manager.py", line 115, in apply_null_result_formatters
    formatted_resp = pipe(params, null_result_formatters)
  File "cytoolz\functoolz.pyx", line 667, in cytoolz.functoolz.pipe
  File "cytoolz\functoolz.pyx", line 642, in cytoolz.functoolz.c_pipe
  File "D:\anaconda\lib\site-packages\web3\_utils\method_formatters.py", line 846, in raise_transaction_not_found
    raise TransactionNotFound(message)
web3.exceptions.TransactionNotFound: Transaction with hash: '0x5c504ed432cb51138bcf09aa5e8a410dd4a1e204ef84bfed1be16dfba1b22060' not found.

Process finished with exit code 1_
**But in fact the transaction hash exists, and the link I used has not expired. I would have to try to rerun it several times to make it work. So what's going on, and how can I fix it?**

**Comment by kclowes** [comment]
Without any other information, I would guess that  it's a new transaction and it's not included on the blockchain when you're asking for it. I don't think this is a bug with web3.py, so I'm going to close this issue. Please feel free to post follow up questions in [our Discord](https://discord.gg/GHryRvPB84) channel.

**Comment by lyc3202** [comment]
Allow me to add a few details:
1. This is not a new transaction, and even the hash of this transaction is used as an example of the use of the official web3 documentation;![image](https://github.com/ethereum/web3.py/assets/81410784/e1478cde-fbd0-4e50-89b7-00cc750fcd71)
2. I must repeat the run several times before the successful run returns the result, otherwise the above error will appear (note that sometimes the hashof the error is different)
Thank you for reading, please help me answer

**Comment by fselmo** [comment]
This seems to me like an issue with your node or provider. I can't reproduce this on my end and this seems like it would be something that would impact quite a few users if it was a problem with the library.

1. Please try to connect to a different provider, just for the sake of testing. I have absolutely no issues when I connect to Infura, for example. Try Infura, Alchemy, etc.

2. Please simplify your setup and try to give a simple code snippet version of how you are connecting. Something like:

```py
from web3 import Web3, HTTPProvider

w3 = Web3(HTTPProvider("https://your.url.here"))

for i in range(10):
    tx = w3.eth.get_transaction("0x5c504ed432cb51138bcf09aa5e8a410dd4a1e204ef84bfed1be16dfba1b22060")
    assert tx.get("blockNumber") == 46147
```

3. This is unlikely to do with your dev environment since there is a null result coming from your node and the null result is causing the formatter to raise a `TransactionNotFound`. However, it sometimes doesn't hurt to try a fresh virtual environment with a fresh `pip install web3`.

Best of luck.

**Comment by lyc3202** [comment]
I changed my node and solved this problem，thank you very much！
