### ISSUE TITLE
JavaScript Ethers serializeTransaction function equivalent

### ISSUE THREAD

**Issue by francestu96** [ethereum/web3.py#3177]
I'm trying to port a **JS** script to **Python** but I'm stack on serializing it.

In particular, on JS ethers library there is the [serializeTransaction](https://docs.ethers.org/v5/api/utils/transactions/#utils-serializeTransaction) function which takes the trx and the **Signature** as **r,v and s** parameters.

I cannot find any way to replicate this function with this Python library. I have those 3 parameter and not the private key but I want to get a raw transaction.

How can I achieve that?

**Comment by kclowes** [comment]
We have a slightly different flow, but check out [Account.sign_transaction](https://eth-account.readthedocs.io/en/stable/eth_account.html#eth_account.account.Account.sign_transaction) docs. That `Account` object is available via `w3.eth.account`. You may also want to check out the docs to [build the transaction](https://web3py.readthedocs.io/en/stable/web3.contract.html#web3.contract.ContractFunction.build_transaction). If you just need the raw, serialized transaction, you can see how it's calculated [here](https://github.com/ethereum/eth-account/blob/b4883627557839bed906c89b93eec0fbbb017ec5/eth_account/_utils/legacy_transactions.py#L59). Beware that anything under `_utils` we consider internal and it may break on a minor version release. We also have some [signing docs](https://web3py.readthedocs.io/en/stable/transactions.html) that you might find useful.

This isn't a problem with the library, so I'm going to close. In the future, since this is a usage question it's better asked in our [Discord](https://discord.gg/GHryRvPB84).
