### ISSUE TITLE
Disconnected from ETH websocket after timeout error 

### ISSUE THREAD

**Issue by germor197** [ethereum/web3.py#3197]
* Version: x.x.x
* Python: 3.9
* OS: windows

i'm trying to listen to eth websocket using python's web3 library, particularly listening to log events.

async def ws_v2_subscription_context_manager_example():

The code works great, im able to listen to logs in real time but thing is if i don't get events for 60 seconds conection will timeout, giving me this error:

`Caching response: response_id=-1, cache_key=6bb61e3b7bce0931da574d19d1d82c88, response={'jsonrpc': '2.0', 'id': -1, 'error': {'code': -32000, 'message': 'Subscription timed out'}}`

 My theory is that this client, being a free service it disconnects automatically 60 seconds after no event has been received, or at least i didn't find any way to refresh that timeout.

I repost the code i posted on ethereum stackexchange:

`async def ws_v2_subscription_context_manager_example():
while True:
    try:
        async with AsyncWeb3.persistent_websocket(
            WebsocketProviderV2("wss://ethereum.publicnode.com")
        ) as w3:

            subscription_id = await w3.eth.subscribe("logs", subscription_params)
            while not unsubscribed:
                    async for response in w3.ws.listen_to_websocket():
                        print(response)`

I managed to keep the connection alive for some more time by unsubscribing and subscribing every 60 seconds when there are no events. So far, it's been working for me, but it's obviously far from ideal.
I also tried to consult the node service documentation, but it doesn't have any (publicnode; wss://bsc.publicnode.com), and the team that works on that client is "Allnodes," which is obviously a paid service.

One detail I didn't mention is that with another free client, this issue doesn't occur; the connection stays alive until I want. Clearly, the problem is with this specific client. The thing is, I also need a Binance Smart Chain client and haven't found any free ones to use, so I'm sticking with this.

I'm not a good programmer, so my question would be: What advice would you give me to establish a connection to a free BSC node? Maybe my trick to connect and disconnect is good for now, but I'd love to hear an opinion from someone who really knows.

**Comment by fselmo** [comment]
Ah, I see. I would indeed say this "issue" is due to the free tier node service. There won't really be an elegant way to handle this. I did ask you to open an issue here from the stack exchange but since you mention another service works just fine, and we do try to keep our issues section reserved for actual issues with the library, I am going to close this as it doesn't appear to be an issue with the library itself.

You might be able to keep the subscription open by spinning out a background task with `asyncio.create_task` that makes some call like `eth_blockNumber` every 30 or 40 seconds. Again, not super elegant, but at this point you're dealing with trying to keep a free tier service alive and not debugging an issue with *web3.py*.

I also suggest asking the question in the [Ethereum Python Discord](https://discord.gg/GHryRvPB84) server as there are plenty of BSC users with experience in websockets and with different tiered third-party services. Best of luck.

---
*edit:* Unfortunately I don't actually think the background task idea may work since it's likely related to your subscription not returning a response within the 60 second window. Others in that Discord may be able to provide you with a better BSC service to use. I don't have experience with BSC but this would likely be the best path to take.

**Comment by germor197** [comment]
Yes, i tried doing that in the first place but it didn't work, gonna check that DS. Sorry for the post, bye!
