### ISSUE TITLE
can we run this with python2

### ISSUE THREAD

**Issue by ywl19891989** [ethereum/web3.py#3283]
* Version: x.x.x
* Python: 2.7
* OS: osx/linux/win
* `pip freeze` output

```
can we run this with python2
```

### What was wrong?

Please include any of the following that are applicable:

* The code which produced the error
* The full output of the error
* What type of node you were connecting to.

### How can it be fixed?

Fill this section in if you know how this could or should be fixed.

---
**Note:** We prefer to use issues to track our work. If you think you've encountered a bug in web3py or 
have a feature request, you're in the right place. If you have implementation or usage questions, 
please refer to our [documentation](https://web3py.readthedocs.io/en/latest/) and/or join the conversation 
on [discord](https://discord.gg/GHryRvPB84).

**Comment by pacrob** [comment]
`web3.py` does not officially support anything earlier than python 3.7, soon to be 3.8. Earlier versions of python 3 may still be mostly functional, but I doubt it would work with python 2.

`web3.py<4` did support python 2, so if that's your only option you could try it, but a LOT has changed in the library since then.
