### ISSUE TITLE
batch request bug

### ISSUE THREAD

**Issue by Azleal** [ethereum/web3.py#3446]
### What happened?

when using `batch_requests` to make multiple request to bsc node. batch requests under `eth` running as expected. however, if I add `provider.make_request` in batch request, errors occurred. 
```
ValueError: too many values to unpack (expected 2)
```

use the code snippet below to reproduce.

### Code that produced the error

```python
import asyncio

from web3 import AsyncWeb3
from web3.middleware import ExtraDataToPOAMiddleware

rpc_url = 'https://docs-demo.bsc.quiknode.pro/'

w3 = AsyncWeb3(AsyncWeb3.AsyncHTTPProvider(rpc_url), middleware=[ExtraDataToPOAMiddleware])

async def run_batch_request_success():
    async with w3.batch_requests() as batch:
        batch.add(w3.eth.get_block(40975701))
        batch.add(w3.eth.get_block(40975702))
        await batch.async_execute()
    print('run_batch_request_success done\n\n')

async def run_batch_request_error():
    async with w3.batch_requests() as batch:
        batch.add(w3.eth.get_block(40975701))
        batch.add(w3.eth.get_block(40975702))
        batch.add(w3.provider.make_request('trace_block', [40975702]))
        await batch.async_execute()
    print('run_batch_request_error done\n\n')

if __name__ == '__main__':
    asyncio.run(run_batch_request_success())
    asyncio.run(run_batch_request_error())
```

### Full error output

```shell
run_batch_request_success done


Traceback (most recent call last):
  File "/root/batch.py", line 27, in <module>
    asyncio.run(run_batch_request_error())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/root/batch.py", line 22, in run_batch_request_error
    await batch.async_execute()
  File "/usr/lib/python3.11/site-packages/web3/_utils/batching.py", line 179, in async_execute
    responses = await self.web3.manager._async_make_batch_request(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/web3/manager.py", line 460, in _async_make_batch_request
    [
  File "/usr/lib/python3.11/site-packages/web3/manager.py", line 462, in <listcomp>
    for (method, params), _response_formatters in unpacked_requests_info
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 2)
```

### web3 Version

7.0.0b9

### Python Version

3.12.4

### Operating System

osx/linux

### Output from `pip freeze`

```shell
aiohappyeyeballs==2.3.4
aiohttp==3.10.1
aiosignal==1.3.1
annotated-types==0.7.0
attrs==24.1.0
bitarray==2.9.2
certifi==2024.7.4
charset-normalizer==3.3.2
ckzg==1.0.2
cytoolz==0.12.3
eth-account==0.13.1
eth-hash==0.7.0
eth-keyfile==0.8.1
eth-keys==0.5.1
eth-rlp==2.1.0
eth-typing==5.0.0b3
eth-utils==5.0.0b1
eth_abi==5.1.0
frozenlist==1.4.1
hexbytes==1.2.1
idna==3.7
multidict==6.0.5
packaging==23.1
parsimonious==0.10.0
pycryptodome==3.20.0
pydantic==2.8.2
pydantic_core==2.20.1
pyparsing==3.0.9
pyunormalize==15.1.0
regex==2024.7.24
requests==2.32.3
rlp==4.0.1
toolz==0.12.1
types-requests==2.32.0.20240712
typing_extensions==4.12.2
urllib3==2.2.2
web3==7.0.0b9
websockets==12.0
yarl==1.9.4
```

**Comment by Azleal** [comment]
hi @fselmo @pacrob please take a look at this issue. am i misusing batch request or is this a bug. thanks

**Comment by fselmo** [comment]
@Azleal I have a few things to add here.

1. Yes, batch request is not meant to be used with the `make_request` method directly. The documentation can use some clarification there but it requires a method to be wrapped around a *web3.py* `Method` class in order to properly handle batching or to even be aware that batching is in progress.

2. It will somewhat depend on the client you're connecting to and how they handle requests vs batched requests, but, _generally_, the overhead of creating a batch of calls for an async provider will be greater than simply using `asyncio.gather()`. I took your sample as inspiration for a quick benchmark:

```py
rpc_url = HTTP_LOCAL
w3 = AsyncWeb3(
    AsyncWeb3.AsyncHTTPProvider(rpc_url), middleware=[ExtraDataToPOAMiddleware]
)
START_BLOCK = 1111111
NUM_BLOCKS = 500


async def run_batch_requests():
    start_time = time.time()
    async with w3.batch_requests() as batch:
        for block in range(START_BLOCK, START_BLOCK - NUM_BLOCKS, -1):
            batch.add(w3.eth.get_block(block))
        await batch.async_execute()
    print(f"run_batch_requests done in {time.time() - start_time} seconds\n\n")


async def run_requests_with_asyncio_gather():
    start_time = time.time()
    await asyncio.gather(
        *[
            w3.eth.get_block(block)
            for block in range(START_BLOCK, START_BLOCK - NUM_BLOCKS, -1)
        ]
    )
    print(
        f"run_requests_with_asyncio_gather done in {time.time() - start_time} "
        "seconds\n\n"
    )


asyncio.run(run_batch_requests())
asyncio.run(run_requests_with_asyncio_gather())
```

output:
```
run_batch_requests done in 0.20206618309020996 seconds
run_requests_with_asyncio_gather done in 0.17958927154541016 seconds
```

I'm not sure if you have a particular use case for batching over `asyncio.gather()` but if you're simply looking to make many concurrent calls, the latter will almost always be favored. Batching will be of great help over a synchronous connection, such as one established with the `HTTPProvider` class.

---

It looks like your current options are:

- Use `asyncio.gather()` and keep making use of `async_w3.provider.make_request()`.

or

- Create an async version of the `Tracing` module that is present on the `Web3` class and use `async_w3.tracing.trace_block()` within your batch if you absolutely need to use batching for your application.

I will make a note to update the documentation and I'll try to add a quick `AsyncTracing` module as well but I'm going to close this issue for now as it isn't a bug based on the usage examples.

**Comment by Azleal** [comment]
@fselmo thank you for your reply. I was just trying the recently added features in `7.0.0b9`, prior to `7.0.0b6` I can only use `asyncio.gather()` to run batch request. and I'll follow your advice to use back `asyncio.gather()`.

**Comment by Azleal** [comment]
@fselmo btw, for the second option
> Create an async version of the `Tracing` module that is present on the `Web3` class and use `async_w3.tracing.trace_block()` within your batch if you absolutely need to use batching for your application.

does it mean that I can create a PR for this?

**Comment by fselmo** [comment]
> does it mean that I can create a PR for this?

That would be great. Take a look at how the `AsyncEth` class is organized and how the `tracing` module is added to the modules in the `main.py` that loads during `Web3` init to emulate it for async. If you need any help feel free to reach out.

We are currently in a code freeze until we release `v7` stable. Being that this is a feature, we may or may not merge it in before the stable release but either way it would be welcomed and merged at some point.

**Comment by fselmo** [comment]
@Azleal, I wasn't near my computer when I answered yesterday but if you're interested (and no pressure)... It would be best to add the `AsyncTracing` class to [this same file](https://github.com/ethereum/web3.py/blob/4489992e235f591363fcf410d54270120b7efe2c/web3/tracing.py#L40-L40), below the `Tracing` class, since they are fairly short classes. We usually separate async code that exists in the same file as sync with a `# -- async -- #` separator within the file ([e.g.](https://github.com/ethereum/web3.py/blob/main/web3/main.py#L419)) for readability. And [this is where](https://github.com/ethereum/web3.py/blob/main/web3/main.py#L155-L166) its added to the `AsyncWeb3` class as `"tracing": AsyncTracing`, just like how `Tracing` is added to the `Web3` class below it.

**Comment by Azleal** [comment]
> @Azleal, I wasn't near my computer when I answered yesterday but if you're interested (and no pressure)... It would be best to add the `AsyncTracing` class to [this same file](https://github.com/ethereum/web3.py/blob/4489992e235f591363fcf410d54270120b7efe2c/web3/tracing.py#L40-L40), below the `Tracing` class, since they are fairly short classes. We usually separate async code that exists in the same file as sync with a `# -- async -- #` separator within the file ([e.g.](https://github.com/ethereum/web3.py/blob/main/web3/main.py#L419)) for readability. And [this is where](https://github.com/ethereum/web3.py/blob/main/web3/main.py#L155-L166) its added to the `AsyncWeb3` class as `"tracing": AsyncTracing`, just like how `Tracing` is added to the `Web3` class below it.

@fselmo Thank you, these details are helpful, I'll use this references and try to add `AsyncTracing` class.
