### ISSUE TITLE
ImportError: cannot import name 'w3'

### ISSUE THREAD

**Issue by sulkhanp** [ethereum/web3.py#483]
* Version: Latest Beta (v4 beta 3)
* Python: 3.6
* OS: win

### What was wrong?

When compiling, python sometimes errors with 'ImportError: cannot import name 'w3'' and sometimes it doesn't. (I tried without changing anything in code, after clicking Run several times, it imports w3) Here are my imports: 
import json, time, web3
from web3.auto import w3
from web3.contract import ConciseContract

### How can it be fixed?

Clicking run several times fixes it.

**Comment by veox** [comment]
This happens to me consistently if there's literally nothing to connect to - i.e. neither the HTTP nor IPC providers are reachable, e.g. since there's no node running.

If the underlying cause does turn out to be the above, then the issue _could_ manifest when no provider is available for other reasons, e.g. due to node overload, OS blocking (including firewall rate-limiting), etc..

**Comment by carver** [comment]
Also note that many nodes require some time to initialize their RPC interface, so if you start up the node and attempt to immediately import `w3`, it won't work yet. Give it some time and/or watch the logs for your node.

**Comment by carver** [comment]
Hopefully #485 will address this issue for you. I'll close this in favor of that tracking issue.
