### ISSUE TITLE
Return address are only checksum addresses if returned from a contract.call()

### ISSUE THREAD

**Issue by berndbohmeier** [ethereum/web3.py#515]
* Version: 3.16.4
* Python: 3.5
* OS: linux

### What was wrong?
A contract call like `contract.call().function()` returns a checksum address
Every other web3 call however like web3.eth.coinbase returns non checksum addresses. 
This is inconsistent.

### How can it be fixed?
Always return checksum addresses

**Comment by pipermerriam** [comment]
@berndbohmeier this is a bug we'll get fixed.  If perhaps you're running into this because of tests where you are doing `assert returned_addr == expected_addr`, you can replace this with `assert eth_utils.is_same_address(returned_addr, expected_addr)` and that will return true for any two recognized address formats that represent the same address.

**Comment by dylanjw** [comment]
closing, because v4 stable is released which resolves this issue.
