### ISSUE TITLE
Web3.py excepts ASCII/UTF-8 input instead of HEX for personal.sign.

### ISSUE THREAD

**Issue by rohithpr** [ethereum/web3.py#526]
* Version: web3==4.0.0b4 (faced the same on older versions too)
* Python: 3.6.3
* OS: osx

* Browser: Chrome with MetaMask 3.13.2

### What was wrong?

There's a difference in the input format requirements between web3.py and web3.js for the methods `web3.personal.sign` and `web3.personal.ecRecover` (and probably others). I couldn't find a "standard" as such that defined what the correct params should be and am guessing that web3.js is considered as the de-facto standard so the deviation is in web3.py.

https://gitter.im/ethereum/web3.py?at=5a3fba255355812e571247d6

I'm running geth `1.7.3-stable` as follows:

```
geth --dev
```

In python:

```
from web3 import Web3, IPCProvider
web3 = Web3(IPCProvider('/path/to/geth.ipc'))
message1 = '0x68656C6C6F'
signature = web3.personal.sign(message1, web3.eth.coinbase, '')
verified_address = web3.personal.ecRecover(message1, signature)
print('Address matches: ', web3.eth.coinbase.lower() == verified_address.lower(), ' ', verified_address)
```

Output: `Address matches:  True   0x08beac2d1f1493f7f477f042f8d2dedcad7ac1f8`

However, on running ecRecover in the browser using that signature I get a different address.

```
> web3.personal.ecRecover('0x68656C6C6F', '0x44972d48e51ceeae93a36696295d7074c1ba797548f92fe88489493dc677ef504d12220561b1109b8cb0956ee67621995d2247fa211f9ca47939bd37abf27e6e1b', console.log)
null "0x66c37d74d68f707ea6478549bec2198b5fccfb92"
```

In order to get the correct address in the browser on running ecRecover the input message for `personal.sign` in web3.py should be `hello` instead of `0x68656C6C6F`.

```
message2 = 'hello'
signature = web3.personal.sign(message2, web3.eth.coinbase, '')
verified_address = web3.personal.ecRecover(message2, signature)
verified_address, signature
```

Output:

`('0x08beac2d1f1493f7f477f042f8d2dedcad7ac1f8', '0x56db7c790d3ded291592c48a90ef785408c8db59ed7805c4de4255a2fe7c4da5099d6f713c23488dd6f3c633406293117c402089e1119429d69dea590987f26b1c')`

In the browser:

```
> web3.personal.ecRecover('0x68656C6C6F', '0x56db7c790d3ded291592c48a90ef785408c8db59ed7805c4de4255a2fe7c4da5099d6f713c23488dd6f3c633406293117c402089e1119429d69dea590987f26b1c', console.log)
null "0x08beac2d1f1493f7f477f042f8d2dedcad7ac1f8" // Correct address
```

The same is applicable for a message signed using web3.js and being verified using web3.py.

Note: web3.js throws an error if the message is not encoded as hex.
<img width="598" alt="screen shot 2017-12-26 at 1 56 34 pm" src="https://user-images.githubusercontent.com/10276811/34351757-9b1ea8c6-ea44-11e7-92ea-ac80576232bf.png">

### How can it be fixed?

Throw an error if the "message" passed to these methods is not hex encoded.

Also, it is possible that the library itself is encoding the message as hex (I haven't gone through the code yet) and that should be avoided in order to maintain consistency.

**Comment by carver** [comment]
Yeah, the personal module doesn't get a lot of love, partially because it is not standard across geth and parity.

This might be one of those places where deviating from the web3.js implementation is a cleaner API and more pythonic. In your example, the hex-encoded string `'0x68656C6C6F'` does not seem like the most natural representation of the message that you're signing. The "truest" representation of the message is `bytes` and the fact that `'hello'` was supported as a string is an accidental side-effect of old py2 support code in eth-utils. So the best answer is that `b'hello'` is the message that you're signing.

My alternative proposed solution is to:

- [ ] Only accept `bytes` type in the message argument, rejecting `str` as a `TypeError` that guides how to convert text or hex to bytes
- [ ] Document `w3.personal.sign` (which appears to not be documented *at all* at the moment).
- [ ] Document examples of how to sign both text and binary messages, something like:

```py
from web3.auto import w3
w3.personal.sign('hello'.encode(), w3.eth.coinbase, 'account-password')

# or
msg = w3.toBytes(hexstr='0x68656C6C6F')
w3.personal.sign(msg, w3.eth.coinbase, 'account-password')
```

Another reasonable alternative is to set up `sign()` to take keyword args like this does: http://web3py.readthedocs.io/en/latest/web3.eth.account.html#web3.account.Account.sign
