### ISSUE TITLE
web application using web3.py

### ISSUE THREAD

**Issue by vijaysagi** [ethereum/web3.py#540]
* Python: 2.7
* OS: ubuntu

I am new to block chain technology. pls guide me where-ever possible  

MY requirement is as follows: 

Using webcam i need to take a detect the face and extract the face vectors from it,  later on we do face recognition by comparing the face  vectors and display the appropriate image on web page. 

 The following are the steps carried out:  
1.  using tracking.js we are able to detect the face and save the image in temporary storage 
2.  using python we are able to extract the face vectors and store it in mysql DB(key,value) 
3.  The face vectors are stored in mysql DB and images are stored in filesystem. 
4.  While face recognition, we compare face vectors in mysql DB and show the appropriate image from the filesystem.   

The following are the queries from the above: 

 Q1) how can i use the existing application to store all images in IPFS and retrieve it based on the need.  
Q2) Once web3.py is installed can i use the existing REST services to share data across the web. 

Q3) Can images in the IPFS block be restricted to specific people.   

Thanks 
vijay

**Comment by carver** [comment]
Why do you want to use a blockchain for this application? It seems like a standard (web2) approach might be a very reasonable way to share static data.

**Comment by vijaysagi** [comment]
I want to have secure common dynamic storage for all images(digital identities) which can be used across all the clients with privilege access.

**Comment by carver** [comment]
Understood. Because all blockchain data is inherently public, you would need some kind of encryption mechanism on top of the published data. It's not impossible, but is not currently a feature built into web3.py. I'd try looking around ethereum.stackexchange for info on encrypting data using an ethereum account.

Since this isn't a currently planned feature, this issue is being closed as off-topic for the web3.py repository. Good luck!
