### ISSUE TITLE
is there plan for ruby interface(web3.rb)?

### ISSUE THREAD

**Issue by yhk1038** [ethereum/web3.py#548]
### What was wrong?

Is there any plan for ruby interface?

**Comment by carver** [comment]
Check out http://www.ethdocs.org/en/latest/connecting-to-clients/index.html which points to https://github.com/DigixGlobal/ethereum-ruby

It doesn't look like it's maintained, though. I haven't heard of anything else, but I'm not really plugged into that community.

Are you volunteering? :-P

Closing this issue, since it isn't a web3.py issue. Good luck!

**Comment by yhk1038** [comment]
Thanks for your answer!

I'll check it first. I wonder how it has progressed.

I would be willing to volunteer if I could. :)

If it does, I want to be able to create a thread again. See you then!
