### ISSUE TITLE
Web3.toText(hexstr='') - 'utf-8' codec can't decode

### ISSUE THREAD

**Issue by bluebirdly** [ethereum/web3.py#603]
* Version: x4.0.0b6
* Python: 3.6.4
* OS: osx

I'm reading the input fields of pending transactions in the txpool (using txpool.content) and trying to convert it into text using:
```
hex_in = '0x338b5dea'
text_out = Web3.toText(hexstr=hex_in)
print('Result: ', text_out)
```

I'm getting the error:
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
`
Any ideas please?

**Comment by pipermerriam** [comment]
UTF8 is not able to encode all of the single byte values.  It's annoying but it's not a bug.  If you need a text representation you have to pick a different encoding.

**Comment by bluebirdly** [comment]
It's the encoding used by web3.py 'web3.txpool.content', how can i change
that? Can't find any reference in the docs.

**Comment by carver** [comment]
@bluebirdly the data in transactions can be arbitrary binary data (ie~ there is no single encoding to use). In order to properly decode them, you would need to look up the ABI of each contract that the transactions are interacting with. Transactions that send arbitrary data and are NOT sending to a contract are a guessing game, there's no way to know what encoding scheme they used, other than guess and check.

In general, if you want to take a long byte array and see parts of it that decode with utf-8, even if other parts don't, then you'll want to directly use python utilities for decoding, with replacement of failed characters. Or you could try decoding with latin-1 to see some simple characters that match.
