### ISSUE TITLE
application deployment  architecture

### ISSUE THREAD

**Issue by vijaysagi** [ethereum/web3.py#609]
* Version: 16.04
* Python: 2.7
* OS: ubuntu

My question is more towards application deployment  architecture:

We are building a web application using ethereum which will detect the faces and store the images locally on the hard drive. As part of on-premise model, i want to deploy the app for every client in safe and efficient manner. 

Q1) on client side,  if i deploy the application on private ethereum can i store the images outside the block. if yes, how can i invoke the images from web app) .

Q2) on the client side, if there is network failure can the webapp run seamlessly.

Q3) can i remotely upgrade the private ethereum block 

Q4) If some transactional data is stored in the block and if the size of the block is full. Can we still run the application or will it lead to hung state.

Thanks

**Comment by carver** [comment]
These architectural questions are outside of the scope of this web3.py project. I recommend checking out http://ethereum.stackexchange.com/

Note that they, like anyone you are asking for help, will be more excited & able to assist if you show more work: what options have you considered? what happened when you attempted it? etc. Otherwise it is about as fun as doing someone else's homework.
