### ISSUE TITLE
Multiple Providers Call to highest block number

### ISSUE THREAD

**Issue by MichaelRazum** [ethereum/web3.py#691]
* Version: latest
* Python:3.5
* OS: win

### What was wrong?
I think it is wrong (not 100% sure )! Right now I'm using infura as HTTP Provider and want to add a localhost provider running geth. So the natural way would be: 
`web3 = Web3([geth_local_host_provider, infura_provider])`

Now as I understand web3 makes always the first request to geth_local_host_provider and if it fails it tries infura_provider. In my case sometimes geth get out of sync. So the actual block number is different. I think the right strategy would be to make the "request" to the HTTP Provider with the highest block.

### How can it be fixed?
Check first the block's of every provider and filter if any provider in the list has a lower block number.

**Comment by pipermerriam** [comment]
I don't think your proposed solution will work for us, but I do think this is an issue that we should look into providing at minimum the tools for solving.  This strikes me as something that *should* be solveable with our middleware layer, but I think it may be tough as things currently stand because middlewares don't have visibility across multiple providers.

cc @carver

**Comment by boneyard93501** [comment]
i was looking into something similar to not select infura for stateful interactions. not quite done but checking for blocks as a (user) add-on is a little more manageable.
assuming something like this:
```python
def get_w3() -> Web3:
    uris = [('local','http://127.0.0.1:8545'),
            ('infura','https://ropsten.infura.io/1vy5tbsVeNil32nbTKl5')
           ]
    providers = []
    for uri in uris:
        f = HTTPProvider(uri[1])
        f.__name__ = uri[0]
        providers.append(f)
    return Web3(providers)
```

something like that will get you the winning provider:

```python
def select_provider(providers: list) -> HTTPProvider :
    selection = {}
    for p in providers:
        result = p.make_request('eth_blockNumber',[])
        block_int = int(result['result'],16)
        if selection.get('winner') is None:
            selection['winner'] = p
            selection['block'] = block_int
        if block_int > selection['block']:
            selection['winner'] = p
            selection['block'] = block_int

    return selection['winner']
``` 
if select_providers() actually returned a (ordered by block size provider) list preceding the request loop in  _make_request in manager.py,  you'd end up with the desired result ... at least that's the entry point i was eying for avoiding the infura provider if need be.

**Comment by pipermerriam** [comment]
The issue with pushing this logic into the manager is that it's forces it onto everyone.  While it's going to be *common* for people to want to use the provider with the highest block number, there are other selection criteria that people may want to use.

So whatever mechanism we use, it's going to be a hard requirement that it's something that users can configure.  One example might be that people want to use the provider which returns a response the quickest.  Some users may not want to overhead of making two extra requests for each JSON-RPC request they make just to check block heights.

Here is my current best idea.

1. Add a new method to the `Manager` class, `Manager.get_providers(method, params)`
2. The default implementation of `Manager.get_providers(..)` is to simply return `self.providers`.
3. Modify `Manager._make_request` to use the return value of `Manager.get_providers(...)` instead of directly accessing `self.providers` in the request loop.

Then, you can create a new `Manager` class, `HighestBlockManager` which overrides the `get_providers` method, returning the list of providers ordered by their block numbers (highest to lowest).

**Comment by boneyard93501** [comment]
@pipermerriam totally agree. i don't want to pay for the overhead as a default. i should have addressed @MichaelRazum explicitly. it's somewhat trivial to implement on a per use case and providing a couple implementation examples might be more useful.  
as an explicit handler:
```python
def w3(web3=web3, logger=None, warning_msg=True):
    '''
        order providers by highest block number
        optionally provide warning for stale/dead HTTPProviders
    '''
    def get_block_int(p):
        return int(p.make_request('eth_blockNumber',[])['result'],16)

    good_providers, bad_providers = [], []
    for p in web3.providers:
        try:
            good_providers.append((p,get_block_int(p)))
        except Exception as e:
            bad_providers.append((p,e))

    if warning_msg and len(bad_providers) > 0:
        vals = (bad_providers, datetime.datetime.utcnow())
        msg = 'Not all of your HTPPProviders are able to connect: {},{}'.format(*vals)
        if logger is not None:
            logger.warning(msg)
        else:
            msg = 'Warning: ' + msg
            sys.stdout.write(msg)

    web3.manager.providers = [p[0] for p in sorted(good_providers,key=lambda x: x[1])]
    return web3
```  

after fiddling with it a bit more, i'd probably sort the providers as stoppable/pausable background task (as a user implementation):
```python
def threaded_provider_ranker(web3,t_stopper,snoozalito=5.0):
    def get_block_int(p):
        return int(p.make_request('eth_blockNumber',[])['result'],16)

    while not t_stopper.is_set():
        try:
            good_providers, bad_providers = [], []
            for p in web3.providers:
                try:
                    good_providers.append((p,get_block_int(p)))
                except Exception as e:
                    bad_providers.append((p,e))

            # <snip>

            if len(good_providers) > 0:
                web3.manager.providers = [p[0] for p in sorted(good_providers,key=lambda x: x[1])]
        except (KeyboardInterrupt, SystemExit):
            pass

        time.sleep(snoozalito)

# ....
t_stopper = threading.Event()
t = threading.Thread(target=threaded_provider_ranker, args=(web3,))
t.start()
...
# t_stopper.set() when you're sick of it
...
t.join()
```
i'd keep the code base lean and clean and add options as examples.  i can clean above up some for documented examples. if you want.

**Comment by MichaelRazum** [comment]
@boneyard93501 
Thanks for the code snippet 👍 

One more question regarding this topic. We were able to find the right providers. 

Now we are sending a Transaction:  `w3.eth.sendRawTransaction(rawTransaction)`.

What happens at this, is it a good Idea to send the rawTransaction to all providers? For example to get a bit faster execution. 
As I understand right now w3 sends the request to the first provider and then if it fails it sends it to the second provider and so on (please correct me if that is wrong). 

Thanks for your answers!

**Comment by pipermerriam** [comment]
With the caching middlewares, it should be reasonably easy to setup provider level caching for each of the providers in question which would greatly reduce the request overhead, especially in cases where there's a lot of requests going out since it'd cache the `eth_blockNumber` request for an amount of time equal to the current average block time.

I'd be supportive of having some different manager classes like this available in the web3 codebase assuming there were some good examples of how to use them.

**Comment by boneyard93501** [comment]
@pipermerriam  i'll look at it over the weekend/early next week.

**Comment by pipermerriam** [comment]
> is it a good Idea to send the rawTransaction to all providers?

This is another case where custom manager logic would be nice.  More theoretical functionality might be the ability to register specific functionality for specific JSON-RPC endpoints.

- for `eth_sendRawTransaction` -> broadcast to all providers.
- for `eth_getTransactionReceipt` -> use provider with highest block number.
- for `eth_sendTransaction` -> only send to local provider.

Some concise way of declaring this functionality and registering new rules would be nice.

**Comment by boneyard93501** [comment]
ha, i've been messing around with rxpy on and off trying to do a few of those things on top of web3py. any appetite for rx ? in my little journey i even stumbled upon an async rxpy implementation that at least superficially looks quite promising, [aioreactive](https://github.com/dbrattli/aioreactive), and adds a bit of a future-proving should asyncio be a package enhancement down the road.

**Comment by pipermerriam** [comment]
We *try* to be very conservative with the dependencies we adopt.  I'm don't see a need for a framework to accomplish this functionality.

**Comment by boneyard93501** [comment]
mind if i PR something, rather incomplete, later today and mark it WIP? i'm gonna be out of pocket for a few days starting tonight ... day job, food, etc.

**Comment by pipermerriam** [comment]
@boneyard93501 go for it.

**Comment by carver** [comment]
Can all of this happen outside of web3? An over-simplified example:

```py
w3_local = Web3(...geth.ipc...)
w3_remote = Web3(...infura...)

class MostRecentWeb3:
  def __init__(self, *web3s):
    self.web3s = web3s
  def __getattr__(self, attr):
    w3 = max(self.web3s, key=lambda w3: w3.eth.blockNumber)
    return getattr(w3, attr)

w3 = MostRecentWeb3(w3_local, w3_remote)
```

**Comment by boneyard93501** [comment]
@carver  at cursory glance, don't see why not ... but as i'm typing this the old gut feeling is rapidly moving toward queasy  :)

**Comment by pipermerriam** [comment]
@carver 

> Disclaimer: I'm not yet convinced this proposed API is necessary or good.  Merely exploring the idea.

I *think* that the following use cases are what we're trying to cover.

1. provider selection based on the call parameters (`meth_a` to Provider A, `meth_b` to Provider B).
2. provider selection based on call result (first to respond, highest block)

My analysis:

- your solution works fine for number 2.  
- your solution has a 1:1 mapping to a custom `Manager` class based solution.
- number 1 is hard without a custom `Manager` class (prove me wrong and we can close this issue).

**Comment by carver** [comment]
> provider selection based on the call parameters (meth_a to Provider A, meth_b to Provider B)

I think that the extra work of keeping two instances of w3 around pays dividends in code clarity:

```py
w3 = Web3([remote_provider, local_provider])

w3.eth.sendTransaction(...)  # this one calls the local
w3.eth.getBalance(...)  # this one calls the remote
```

```py
w3_remote = Web3(remote_provider)
w3_local = Web3(local_provider)

w3_local.eth.sendTransaction(...)
w3_remote.eth.getBalance(...)
```

(None of this is meant to discourage @boneyard93501 from exploring the direction, since my opinion is formed without knowing what the api would look like. As a reference point, though, I'm not even convinced that our current multi-provider setup does more good than harm :) )

**Comment by pipermerriam** [comment]
> I'm not even convinced that our current multi-provider setup does more good than harm

I completely agree.  If we don't have anything using it by the time that v5.x is on the horizon we would plan to deprecate and remove it.

**Comment by fselmo** [comment]
stale
