### ISSUE TITLE
sendRawTransaction returns hash but transaction seems to be not broadcasted

### ISSUE THREAD

**Issue by startsts** [ethereum/web3.py#765]
* Version: 4.1.0
* Python: 3.6
* OS: linux

I'm trying to make transaction

Code:

```
from web3 import Web3
etherscan_provider = Web3.HTTPProvider('https://mainnet.infura.io/AEMak0Vu4yDk....')
w3 = Web3(etherscan_provider)

w3.eth.enable_unaudited_features()
tr = {'to': '0x217f1B9735D4c94870775E484F60017e69c091F5', 'value': 1000000000000000, 'chainId': 1, 'gas': 21000, 'gasPrice': w3.toWei('1', 'gwei'), 'nonce': 5,}
signed = w3.eth.account.signTransaction(tr, "0xe2105531564518010d946b740abfbd1262e8...........")
tx = w3.eth.sendRawTransaction(signed.rawTransaction)
tx = w3.toHex(tx)
print("tx",tx)

```

It prints hash of transaction, but transaction never appears at block explorer, so seems to be not broadcasted

**Comment by carver** [comment]
@startsts If that's a real private key, I recommend transferring everything out of there and never using it again. (it's not *super* easy to guess your complete key, but it's now `10^43` times less secure than a properly chosen random private key)

> It prints hash of transaction, but transaction never appears at block explorer, so seems to be not broadcasted

The first thing that stands out is the `nonce`. Has that account already sent 5 transactions?

BTW, you're more likely to get fast answers for questions about how to use web3py on places like https://ethereum.stackexchange.com/

---

I'm closing because it's unlikely that this is a web3py bug. Feel free to keep commenting to try to resolve the issue.
