### ISSUE TITLE
contract reverted(Error in Txn) when send ether to https://kovan.infura.io

### ISSUE THREAD

**Issue by FrancisJen** [ethereum/web3.py#818]
* Version: x.x.x
* Python: 2.7/3.4/3.5
* OS: osx/linux/win

python3.6.5
### What was wrong?
ethereumscan: https://kovan.etherscan.io/tx/0xf11ead8229446be0a2bf388cee16822f81b713fa94a4bfde687159544aa77afb

Contract 0x97b2f257e51da5bd16f6ec34a575c366ffb745c2  
 Warning! Error encountered during contract execution [Reverted] Value: 0.0001 Ether ($0.00) - [CANCELLED]  

### How can it be fixed?
source code

# coding=utf-8
import web3
from web3 import Web3, HTTPProvider
import json
import rlp
from ethereum.transactions import Transaction
import time

class OperationKovan:

	def __init__(self):
		self.url = 'https://kovan.infura.io'
		self.w3 = Web3(HTTPProvider(self.url))

		# 前端充值
		self.R1_CONTRACT_ADDRESS = '0xxxxxxxx'
		self.R1_CONTRACT_PATH  = '/xxx/r1ABI.json'
		with open(self.R1_CONTRACT_PATH) as load_f:
			load_dict = json.load(load_f)
			# print(load_dict)
		self.wallet_address = '0xDecF8962727Cd0465e8228001DCDEa46BA624C2c'
		self.wallet_private_key = 'xxx'

		# 创建R1对象（合约对象）
		self.R1 = self.w3.eth.contract(address=self.R1_CONTRACT_ADDRESS, abi=load_dict)

		self.w3.eth.enable_unaudited_features()

	# 获得区块高度
	def get_block_num(self):
		blockNum = self.w3.eth.blockNumber
		return blockNum

	# 通过合约对象的xx方法获取到充值所需的数据
	def get_recharge_data(self):
		pass

	def send_ether_to_contract(self,amount_in_ether):

		# amount_in_wei = amount_in_ether * 1000000000000000000;
		amount_in_wei = self.w3.toWei(amount_in_ether, 'ether')

		nonce = self.w3.eth.getTransactionCount(self.wallet_address)

		txn_dict = {
				'to': self.R1_CONTRACT_ADDRESS,
				'value': amount_in_wei,
				'gas': 195000,
				'gasPrice': self.w3.toWei('11', 'gwei'),
				'nonce': nonce,
				'chainId': None
		}

		signed_txn = self.w3.eth.account.signTransaction(txn_dict, self.wallet_private_key)
		txn_hash = self.w3.eth.sendRawTransaction(signed_txn.rawTransaction)
		txn_receipt = None
		count = 0
		while txn_receipt is None and (count < 30):
			txn_receipt = self.w3.eth.getTransactionReceipt(txn_hash)
			print(txn_receipt)
			time.sleep(10)

		if txn_receipt is None:
			return {'status': 'failed', 'error': 'timeout'}

		return {'status': 'added', 'txn_receipt': txn_receipt}

if __name__ == '__main__':
	kovan = OperationKovan()
	blockNum = kovan.get_block_num()
	print(blockNum)
	# recharge
	kovan.send_ether_to_contract(0.0001)

**Comment by carver** [comment]
There are a lot of reasons that your transaction might hit an error condition. Figuring out why your transaction is reverting is simplest to do by reading the source of the contract.

Since the problem doesn't appear to be specific to Web3.py, I'm closing the issue. But feel free to continue discussing here. One alternative to consider is https://ethereum.stackexchange.com

You will get better & faster answers if your question has a minimal, complete, and verifiable example (in this case, that means including the contract source): https://stackoverflow.com/help/mcve

One benefit of building an MCVE is that during the process, the answer often becomes clear without needing to post the question at all.
