### ISSUE TITLE
How to transfer tokens from non-`contract.eth.accounts` address?

### ISSUE THREAD

**Issue by paymog** [ethereum/web3.py#848]
* Version: 4.1
* Python: 3.5
* OS: osx

### What was wrong?

I've writing tests for a token which implements the [ERC20 token standard](https://theethereum.wiki/w/index.php/ERC20_Token_Standard). In the constructor of my token I split the currency between two addresses like so:

```
    constructor() {
        symbol = "mytoken";
        name = "MyToken";
        decimals = 18;
        _totalSupply = 100000000000000000000000000;

        balances[0x364ca3F935E88Fbc9e041d2032F996CAc69452e6] = _totalSupply / 2; 
        balances[0x5506195d8111B5e150Fb68Ceba2806c546C5a28B] = _totalSupply / 2;

        Transfer(address(0), 0x364ca3F935E88Fbc9e041d2032F996CAc69452e6,
                 _totalSupply / 2);
        Transfer(address(0), 0x5506195d8111B5e150Fb68Ceba2806c546C5a28B,
                 _totalSupply / 2);
    }
```

On the python side I'm trying to call the `transfer` method from one of these addresses like 

```
    def test_vote_then_move_balance_is_useless(self):
        RANDOM_USER = "0x1111111111111111111111111111111111111112"
        USER_WITH_COINS = "0x5506195d8111B5e150Fb68Ceba2806c546C5a28B"

        # my setUp method creates the contract much like https://github.com/ethereum/web3.py#quickstart
        self.contract_instance.transfer(RANDOM_USER, 10, transact={'from': USER_WITH_COINS})
```

However, when I do this I get the following error: `ValueError: b'U\x06\x19]\x81\x11\xb5\xe1P\xfbh\xce\xba(\x06\xc5F\xc5\xa2\x8b' is not in list` which makes sense because `USER_WITH_COINS` isn't part of `contract.eth.accounts`. How can I perform this transfer? I've thought about using the `approve` mechanism, but that would still require `USER_WITH_COINS` to approve one of the `contract.eth.accounts` accounts which would have the same problem.

**Comment by carver** [comment]
I don't recognize that error message. I would need to see more of the code and the stack trace to help you debug (or preferably a smaller, complete example that isolates the problem).

---

Since this isn't a bug or feature request for Web3.py, I'm closing the issue. But feel free to continue discussing here. One alternative to consider is https://ethereum.stackexchange.com

You will get better & faster answers if your question has a minimal, complete, and verifiable example: https://stackoverflow.com/help/mcve
