### ISSUE TITLE
personal_importRawKey should NOT strip leading 0x from private key.

### ISSUE THREAD

**Issue by Shaptic** [ethereum/web3.py#900]
* Version: 4.2.1
* Python: 3.6.5
* OS: linux

### What was wrong?
When importing a custom account via `personal_importRawKey`, the formatter strips the leading `0x` characters from the private key in the RPC JSON. This causes [ganache](https://github.com/trufflesuite/ganache-cli) to return an error because it expects the leading `0x` when parsing the data. This may, of course, be an error on ganache's part rather than web3's in which case please let me know and I will re-issue it accordingly! The RPC is as follows:

```js
personal_importRawKey
   > {
   >   "jsonrpc": "2.0",
   >   "method": "personal_importRawKey",
   >   "params": [
   >     "59afed4855441d80384bb2bebcb29e03b4892ca21e93505ab7345588b245f1c7",
   >     "test passphrase"
   >   ],
   >   "id": 5
   > }
 <   {
 <     "id": 5,
 <     "jsonrpc": "2.0",
 <     "error": {
 <       "message": "private key length is invalid",
 <       "code": -32000,
 <       "data": {
 <         "stack": "RangeError: private key length is invalid\n..."
```

### How can it be fixed?
In `middleware/pythonic.py`, the following formatters are applied to this API call:

```python
        # personal
        'personal_importRawKey': apply_formatter_at_index(
            compose(remove_0x_prefix, hexstr_if_str(to_hex)),
            0,
        ),
```

It should be removed entirely.

**Comment by carver** [comment]
Unfortunately, it's [not a well specified API](https://github.com/ethereum/go-ethereum/wiki/Management-APIs#personal_importrawkey). (It's also [not standard](https://github.com/ethereum/wiki/wiki/JSON-RPC), it's only in geth and nodes that copy geth.)

Any solution that attempts this should be checked to make sure it still works in geth.

The way hex data is specified in the rest of the JSON-RPC, it usually is prefixed with 0x, so I'm not sure the reason it's stripped here, without git blame-ing. But I imagine there is a reason.

**Comment by reedsa** [comment]
There's a long history here but I discovered the original implementation was checking the length of the private key and stripping the "0x" in [some cases](https://github.com/ethereum/web3.py/commit/b17245aa0c4afe1c1a3954fcb70b39d116a913e7#diff-93c3d415544952636221aca14f9a61f7a095e7e2b3ba43ebcb4bbfbb9c01b996L24).

That implementation would not have worked with Ganache either. Instead of removing the formatter for this edge case I would recommend using a [custom Middleware](https://web3py.readthedocs.io/en/stable/internals.html?ref=snakecharmers.ethereum.org#middlewares) that overrides that formatter in one way or another. If the custom middlware is added in the appropriate layer, it could re-add the `0x` within the custom middleware after the pythonic middleware has run.

Also of note, the geth API has been deprecated in favor of [Clef](https://geth.ethereum.org/docs/tools/clef/introduction) and I am unaware if changes will be made to Ganache's API eventually in that regard.
