### ISSUE TITLE
How make deposits by web3 py ?

### ISSUE THREAD

**Issue by RZeynalov** [ethereum/web3.py#932]
Dear Developers,

I do succeffully transfer tokens and ethers via web3( great thx to web3 developers) . But i faced the problem that making deposits requires another approach that i can not find in web3 now, may be somebody knows how to do and drop small example of code or advice. I d like to make deposits to exchanges like IDEX Thank you all in advance!!!

**Comment by carver** [comment]
This isn't the best place to get support on how to use Web3.py in general.

---

Since this isn't a bug or feature request for Web3.py, I'm closing the issue. You might find that https://ethereum.stackexchange.com is a better resource.

You will get better & faster answers if your question has a minimal, complete, and verifiable example: https://stackoverflow.com/help/mcve
