### ISSUE TITLE
Improve error messages on mismatched argument types

### ISSUE THREAD

**Issue by carver** [ethereum/web3.py#964]
### What was wrong?

When sending an argument with the wrong type to a contract function, people find it difficult to debug and end up frustrated, like in #625

### How can it be fixed?

We largely solve for the *general* case: that multiple functions can exist with the same name. Obviously we have to support that, but it's incredibly common to have names that are unique even without the argument types. In these cases, we can give clearer error messages about exactly which types are expected for which arguments.

For example, we could raise the function:
> ValidationError: a function with name testFunction is defined by the contract, but some argument types don't match:
> -  address _location :heavy_check_mark:
> -  uint256 _reading :heavy_check_mark:
> -  uint256 _minParameter :heavy_check_mark:
> -  uint256 _maxParameter :heavy_check_mark:
> -  bytes32 _codeHash :warning: This argument was supplied as a string that was too long. If you want to supply a hex string, this function only accepts values that are exactly 64 characters (plus 2 for 0x). Alternatively, supply this argument as python native bytes, with a length of 32 bytes. Actually supplied argument: "0xFFFFF..." (length: 67)

**Comment by MatthiasLohr** [comment]
Is there any official documentation, about how to provide the values for several types?

It could help to add some documentation in the Web3 libraries (JS, Python, ...) to provide examples on how to encode specific Ethereum types in these languages/libraries.

**Comment by MatthiasLohr** [comment]
Oh, that would have been good to have had this link yesterday. ;) So first: It seems to be somehow hard to find. I have seen this point "Conventions", but didn't take a deep look into it because it somehow felt far away from my problem.

Yesterday I tried to call a contract with web3py with error (something like) "found (str, bytes[]), need (address, bytes32). For me, at first place, it looked like a a working mapping, because the str object was a (checksum) address hex string and bytes[] was 32 bytes long (actually, it was not, that was the actual problem). 

1. I really would have liked to have had a hint which of these arguments cannot be mapped.
2. A "mapping" table (EVM type - Python type) like the following would be great (in my opinion):
  * `address`: `str` with checksum address, create with `Web3.toChecksumAddress`
  * `bytes32`: `bytes[]` array with exactly 32 bytes.
  * `intX`/`uintX`: `int`
  * ...

If there are multiple possibilities for the mapping, all variants should be listed. I'm not that into Solidity/Web3Py so that I don't know all mappings. But maybe my idea is clear and helps to improve the documentation.

**Comment by MatthiasLohr** [comment]
Why not just "Types"? Conventions can be so much more (Coding Conventions, if you want to start to contribute, Naming Conventions for internal variables, ...). Just "Types" reflects, what the page currently contains.

**Comment by MatthiasLohr** [comment]
Sounds good.

Would also be good to have a link in Smart Contract calling examples (how to convert your Python datatypes to Solidity types, see (e.g.) "ABI Type Conversion").

**Comment by MatthiasLohr** [comment]
Anything new on this? Any chance on getting some more verbose on information what actually went wrong on type conversion when executing code?

**Comment by pipermerriam** [comment]
We'd be happy to review and provide feedback on a pull request if you'd like to take a stab at it.

**Comment by MatthiasLohr** [comment]
The problem is: If I would know how to debug/find out what exactly the problem is, I wouldn't have to write here and ask for more details ;)

**Comment by pipermerriam** [comment]
Here are the two entry points where I expect this functionality would be easiest to add:

https://github.com/ethereum/web3.py/blob/6258d2e1c807aee892481296c7f115399ce6a6f8/web3/_utils/contracts.py#L75-L161

In the case of `find_matching_fn_abi` we already have a good start at an improved error message, so the same pattern could be ported over to `find_matching_event_abi`.  This is probably the smallest and simplest change that would improve things for events in the same way that function lookups have historically been improved.

To further improve the messages, we'll need to do a bit deeper adjustment of the code upon failure to find a match to gather the following data:  For each ABI definition, determine whether it matches each individual criteria (name,number-of-args,argument-types) and then format that data into a single error message detailing each of the function's, their function signatures, and whether they matched the required critera.

(Just dumping this here so that when this does get worked on, it's a bit easier to figure out where to start and what needs to be done)
